// lib/bloc/generators/mapper/mapper_generator.dart
//
// Generates the Mapper class: FeatureState → Domain Entity

class MapperGenerator {
  /// [featureName] – PascalCase name of the feature (e.g., "UserjourneyForm")
  /// [fieldNames] – list of field keys as they appear in state.formValues
  /// [entityClassName] – name of the target domain entity class (e.g., "UserjourneyFormEntity")
  /// [stateClassName] – optional, defaults to "${featureName}State"
  MapperGenerator({
    required this.featureName,
    required this.fieldNames,
    required this.entityClassName,
    this.stateClassName,
  });

  final String featureName;
  final List<String> fieldNames;
  final String entityClassName;
  final String? stateClassName;

  String get _stateName => stateClassName ?? '${featureName}State';
  String get _snakeName => _toSnakeCase(featureName);

  String generate() {
    final mapperName = '${featureName}Mapper';
    final buf = StringBuffer();

    // Correct import paths: adjust according to your project structure.
    // The entity is in ../../domain/entities/
    buf.writeln("import '../../domain/entities/${_snakeName}_entity.dart';");
    // The state is generated by BLoC generator and lives in ../bloc/
    buf.writeln("import '../bloc/${_snakeName}_state.dart';");
    buf.writeln();
    buf.writeln('/// Maps a validated [$_stateName] to a [$entityClassName].');
    buf.writeln('abstract final class $mapperName {');
    buf.writeln('  static $entityClassName toEntity($_stateName state) {');
    buf.writeln('    return $entityClassName(');
    for (final field in fieldNames) {
      // Access value from the formValues map
      buf.writeln("      $field: state.formValues['$field'],");
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln('}');

    return buf.toString();
  }

  // Helper: convert PascalCase/camelCase to snake_case
  String _toSnakeCase(String input) {
    if (input.isEmpty) return input;
    final buffer = StringBuffer();
    buffer.write(input[0].toLowerCase());
    for (int i = 1; i < input.length; i++) {
      final char = input[i];
      if (char.toUpperCase() == char && char != char.toLowerCase()) {
        buffer.write('_${char.toLowerCase()}');
      } else {
        buffer.write(char);
      }
    }
    return buffer.toString();
  }
}