String generateTextForm() {
  final buffer = StringBuffer();


buffer.writeln("	import 'package:flutter/material.dart';	");
buffer.writeln("	import 'package:flutter/services.dart';	");
buffer.writeln("	import 'package:intl/intl.dart';	");
buffer.writeln("		");
buffer.writeln("	import 'FieldValidators.dart';	");
buffer.writeln("		");
buffer.writeln("	enum LabelPosition { floating, top, left, inline }	");
buffer.writeln("	enum ValidationMode { onChanged, onBlur, onSubmit }	");
buffer.writeln("		");
buffer.writeln("	class CustomTextFormField extends StatefulWidget {	");
buffer.writeln("	  final String? label;	");
buffer.writeln("	  final String? hint;	");
buffer.writeln("	  final String? helperText;	");
buffer.writeln("	  final String? errorText;	");
buffer.writeln("	  final bool isMandatory;	");
buffer.writeln("	  final bool isPassword;	");
buffer.writeln("	  final bool isNumber;	");
buffer.writeln("	  final bool isDatePicker;	");
buffer.writeln("	  final bool isTimePicker;	");
buffer.writeln("	  final bool isDateTimePicker;	");
buffer.writeln("	  final LabelPosition labelPosition;	");
buffer.writeln("	  final TextEditingController? controller;	");
buffer.writeln("	  final String? initialValue;	");
buffer.writeln("	  final TextInputType keyboardType;	");
buffer.writeln("	  final IconData? prefixIcon;	");
buffer.writeln("	  final IconData? suffixIcon;	");
buffer.writeln("	  final bool enableSuffix;	");
buffer.writeln("	  final String? dateFormat;	");
buffer.writeln("	  final String? timeFormat;	");
buffer.writeln("	  final String? dateTimeFormat;	");
buffer.writeln("	  final Locale? locale;	");
buffer.writeln("	  final String? Function(String?)? validator;	");
buffer.writeln("	  final List<String? Function(String?)>? validators;	");
buffer.writeln("	  final List<TextInputFormatter>? inputFormatters;	");
buffer.writeln("	  final void Function(String?)? onSaved;	");
buffer.writeln("	  final bool readOnly;	");
buffer.writeln("	  final bool enabled;	");
buffer.writeln("	  final void Function(String)? onChanged;	");
buffer.writeln("	  final TextInputAction? textInputAction;	");
buffer.writeln("	  final TextCapitalization textCapitalization;	");
buffer.writeln("	  final FocusNode? focusNode;	");
buffer.writeln("	  final int? maxLines;	");
buffer.writeln("	  final int? minLines;	");
buffer.writeln("	  final AutovalidateMode? autovalidateMode;	");
buffer.writeln("	  final TextStyle? textStyle;	");
buffer.writeln("	  final InputDecoration? decoration;	");
buffer.writeln("	  final InputDecorationTheme? decorationTheme;	");
buffer.writeln("	  final bool autoFocus;	");
buffer.writeln("	  final EdgeInsetsGeometry? padding;	");
buffer.writeln("	  final double? width;	");
buffer.writeln("	  final double? height;	");
buffer.writeln("	  final Color? fillColor;	");
buffer.writeln("	  final bool showClearButton;	");
buffer.writeln("	  final ValidationMode validationMode;	");
buffer.writeln("	  final DateTime? initialDate;	");
buffer.writeln("	  final DateTime? firstDate;	");
buffer.writeln("	  final DateTime? lastDate;	");
buffer.writeln("	  final TimeOfDay? initialTime;	");
buffer.writeln("		");
buffer.writeln("	  const CustomTextFormField({	");
buffer.writeln("	    super.key,	");
buffer.writeln("	    this.label,	");
buffer.writeln("	    this.hint,	");
buffer.writeln("	    this.helperText,	");
buffer.writeln("	    this.errorText,	");
buffer.writeln("	    this.isMandatory = false,	");
buffer.writeln("	    this.isPassword = false,	");
buffer.writeln("	    this.isNumber = false,	");
buffer.writeln("	    this.isDatePicker = false,	");
buffer.writeln("	    this.isTimePicker = false,	");
buffer.writeln("	    this.isDateTimePicker = false,	");
buffer.writeln("	    this.labelPosition = LabelPosition.floating,	");
buffer.writeln("	    this.controller,	");
buffer.writeln("	    this.initialValue,	");
buffer.writeln("	    this.keyboardType = TextInputType.text,	");
buffer.writeln("	    this.prefixIcon,	");
buffer.writeln("	    this.suffixIcon,	");
buffer.writeln("	    this.enableSuffix = true,	");
buffer.writeln("	    this.dateFormat,	");
buffer.writeln("	    this.timeFormat,	");
buffer.writeln("	    this.dateTimeFormat,	");
buffer.writeln("	    this.locale,	");
buffer.writeln("	    this.validator,	");
buffer.writeln("	    this.validators,	");
buffer.writeln("	    this.inputFormatters,	");
buffer.writeln("	    this.onSaved,	");
buffer.writeln("	    this.readOnly = false,	");
buffer.writeln("	    this.enabled = true,	");
buffer.writeln("	    this.onChanged,	");
buffer.writeln("	    this.textInputAction,	");
buffer.writeln("	    this.textCapitalization = TextCapitalization.none,	");
buffer.writeln("	    this.focusNode,	");
buffer.writeln("	    this.maxLines = 1,	");
buffer.writeln("	    this.minLines,	");
buffer.writeln("	    this.autovalidateMode,	");
buffer.writeln("	    this.textStyle,	");
buffer.writeln("	    this.decoration,	");
buffer.writeln("	    this.decorationTheme,	");
buffer.writeln("	    this.autoFocus = false,	");
buffer.writeln("	    this.padding,	");
buffer.writeln("	    this.width,	");
buffer.writeln("	    this.height,	");
buffer.writeln("	    this.fillColor,	");
buffer.writeln("	    this.showClearButton = false,	");
buffer.writeln("	    this.validationMode = ValidationMode.onSubmit,	");
buffer.writeln("	    this.initialDate,	");
buffer.writeln("	    this.firstDate,	");
buffer.writeln("	    this.lastDate,	");
buffer.writeln("	    this.initialTime,	");
buffer.writeln("	  });	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  State<CustomTextFormField> createState() => _CustomTextFormFieldState();	");
buffer.writeln("	}	");
buffer.writeln("		");
buffer.writeln("	class _CustomTextFormFieldState extends State<CustomTextFormField> {	");
buffer.writeln("	  bool obscureText = false;	");
buffer.writeln("	  late TextEditingController _internalController;	");
buffer.writeln("	  late FocusNode _internalFocusNode;	");
buffer.writeln("	  bool _isFocused = false;	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  void initState() {	");
buffer.writeln("	    super.initState();	");
buffer.writeln("	    obscureText = widget.isPassword;	");
buffer.writeln("	    _internalController = widget.controller ?? TextEditingController(text: widget.initialValue);	");
buffer.writeln("	    _internalFocusNode = widget.focusNode ?? FocusNode();	");
buffer.writeln("	    	");
buffer.writeln("	    _internalFocusNode.addListener(() {	");
buffer.writeln("	      setState(() {	");
buffer.writeln("	        _isFocused = _internalFocusNode.hasFocus;	");
buffer.writeln("	      });	");
buffer.writeln("	      	");
buffer.writeln("	      if (widget.validationMode == ValidationMode.onBlur && !_internalFocusNode.hasFocus) {	");
buffer.writeln("	        _internalFocusNode.context?.findAncestorStateOfType<FormState>()?.validate();	");
buffer.writeln("	      }	");
buffer.writeln("	    });	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  void didUpdateWidget(covariant CustomTextFormField oldWidget) {	");
buffer.writeln("	    super.didUpdateWidget(oldWidget);	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.controller != oldWidget.controller) {	");
buffer.writeln("	      if (oldWidget.controller == null) {	");
buffer.writeln("	        _internalController.dispose();	");
buffer.writeln("	      }	");
buffer.writeln("	      _internalController = widget.controller ?? TextEditingController(text: widget.initialValue);	");
buffer.writeln("	    }	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.controller == null && widget.initialValue != oldWidget.initialValue) {	");
buffer.writeln("	      _internalController.text = widget.initialValue ?? '';	");
buffer.writeln("	    }	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.isPassword != oldWidget.isPassword) {	");
buffer.writeln("	      obscureText = widget.isPassword;	");
buffer.writeln("	    }	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.focusNode != oldWidget.focusNode) {	");
buffer.writeln("	      _internalFocusNode.removeListener(() {});	");
buffer.writeln("	      if (oldWidget.focusNode == null) {	");
buffer.writeln("	        _internalFocusNode.dispose();	");
buffer.writeln("	      }	");
buffer.writeln("	      _internalFocusNode = widget.focusNode ?? FocusNode();	");
buffer.writeln("	      _internalFocusNode.addListener(_handleFocusChange);	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _handleFocusChange() {	");
buffer.writeln("	    setState(() {	");
buffer.writeln("	      _isFocused = _internalFocusNode.hasFocus;	");
buffer.writeln("	    });	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.validationMode == ValidationMode.onBlur && !_internalFocusNode.hasFocus) {	");
buffer.writeln("	      _internalFocusNode.context?.findAncestorStateOfType<FormState>()?.validate();	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  void dispose() {	");
buffer.writeln("	    if (widget.controller == null) {	");
buffer.writeln("	      _internalController.dispose();	");
buffer.writeln("	    }	");
buffer.writeln("	    if (widget.focusNode == null) {	");
buffer.writeln("	      _internalFocusNode.dispose();	");
buffer.writeln("	    }	");
buffer.writeln("	    super.dispose();	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _togglePassword() {	");
buffer.writeln("	    setState(() {	");
buffer.writeln("	      obscureText = !obscureText;	");
buffer.writeln("	    });	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _clearText() {	");
buffer.writeln("	    setState(() {	");
buffer.writeln("	      _internalController.clear();	");
buffer.writeln("	      widget.onChanged?.call('');	");
buffer.writeln("	    });	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Future<void> _pickDate() async {	");
buffer.writeln("	    final pickedDate = await showDatePicker(	");
buffer.writeln("	      context: context,	");
buffer.writeln("	      initialDate: widget.initialDate ?? DateTime.now(),	");
buffer.writeln("	      firstDate: widget.firstDate ?? DateTime(1900),	");
buffer.writeln("	      lastDate: widget.lastDate ?? DateTime(2100),	");
buffer.writeln("	    );	");
buffer.writeln("	    	");
buffer.writeln("	    if (pickedDate != null) {	");
buffer.writeln("	      final format = widget.dateFormat ?? 'yyyy-MM-dd';	");
buffer.writeln("	      _internalController.text = DateFormat(format, widget.locale?.toString()).format(pickedDate);	");
buffer.writeln("	      widget.onChanged?.call(_internalController.text);	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Future<void> _pickTime() async {	");
buffer.writeln("	    final pickedTime = await showTimePicker(	");
buffer.writeln("	      context: context,	");
buffer.writeln("	      initialTime: widget.initialTime ?? TimeOfDay.now(),	");
buffer.writeln("	    );	");
buffer.writeln("	    	");
buffer.writeln("	    if (pickedTime != null) {	");
buffer.writeln("	      final now = DateTime.now();	");
buffer.writeln("	      final fullTime = DateTime(	");
buffer.writeln("	        now.year,	");
buffer.writeln("	        now.month,	");
buffer.writeln("	        now.day,	");
buffer.writeln("	        pickedTime.hour,	");
buffer.writeln("	        pickedTime.minute,	");
buffer.writeln("	      );	");
buffer.writeln("	      final format = widget.timeFormat ?? 'HH:mm';	");
buffer.writeln("	      _internalController.text = DateFormat(format, widget.locale?.toString()).format(fullTime);	");
buffer.writeln("	      widget.onChanged?.call(_internalController.text);	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Future<void> _pickDateTime() async {	");
buffer.writeln("	    final pickedDate = await showDatePicker(	");
buffer.writeln("	      context: context,	");
buffer.writeln("	      initialDate: widget.initialDate ?? DateTime.now(),	");
buffer.writeln("	      firstDate: widget.firstDate ?? DateTime(1900),	");
buffer.writeln("	      lastDate: widget.lastDate ?? DateTime(2100),	");
buffer.writeln("	    );	");
buffer.writeln("	    	");
buffer.writeln("	    if (pickedDate != null) {	");
buffer.writeln("	      final pickedTime = await showTimePicker(	");
buffer.writeln("	        context: context,	");
buffer.writeln("	        initialTime: widget.initialTime ?? TimeOfDay.now(),	");
buffer.writeln("	      );	");
buffer.writeln("	      	");
buffer.writeln("	      if (pickedTime != null) {	");
buffer.writeln("	        final fullDateTime = DateTime(	");
buffer.writeln("	          pickedDate.year,	");
buffer.writeln("	          pickedDate.month,	");
buffer.writeln("	          pickedDate.day,	");
buffer.writeln("	          pickedTime.hour,	");
buffer.writeln("	          pickedTime.minute,	");
buffer.writeln("	        );	");
buffer.writeln("	        final format = widget.dateTimeFormat ?? 'yyyy-MM-dd HH:mm';	");
buffer.writeln("	        _internalController.text = DateFormat(format, widget.locale?.toString()).format(fullDateTime);	");
buffer.writeln("	        widget.onChanged?.call(_internalController.text);	");
buffer.writeln("	      }	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  String? _combinedValidator(String? value) {	");
buffer.writeln("	    if (widget.isMandatory) {	");
buffer.writeln("	      final res = FieldValidators.required(	");
buffer.writeln("	        value,	");
buffer.writeln("	        fieldName: widget.label ?? 'Field',	");
buffer.writeln("	      );	");
buffer.writeln("	      if (res != null) return res;	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    if (value != null && value.isNotEmpty) {	");
buffer.writeln("	      try {	");
buffer.writeln("	        if (widget.isDatePicker) {	");
buffer.writeln("	          DateFormat(widget.dateFormat ?? 'yyyy-MM-dd', widget.locale?.toString()).parseStrict(value);	");
buffer.writeln("	        } else if (widget.isTimePicker) {	");
buffer.writeln("	          DateFormat(widget.timeFormat ?? 'HH:mm', widget.locale?.toString()).parseStrict(value);	");
buffer.writeln("	        } else if (widget.isDateTimePicker) {	");
buffer.writeln("	          DateFormat(widget.dateTimeFormat ?? 'yyyy-MM-dd HH:mm', widget.locale?.toString()).parseStrict(value);	");
buffer.writeln("	        }	");
buffer.writeln("	      } catch (e) {	");
buffer.writeln("	        print('Date parsing error: \$e');	");
buffer.writeln("	        String expectedFormat = '';	");
buffer.writeln("	        if (widget.isDatePicker) {	");
buffer.writeln("	          expectedFormat = widget.dateFormat ?? 'yyyy-MM-dd';	");
buffer.writeln("	          return 'Invalid date format, expected: \$expectedFormat';	");
buffer.writeln("	        } else if (widget.isTimePicker) {	");
buffer.writeln("	          expectedFormat = widget.timeFormat ?? 'HH:mm';	");
buffer.writeln("	          return 'Invalid time format, expected: \$expectedFormat';	");
buffer.writeln("	        } else if (widget.isDateTimePicker) {	");
buffer.writeln("	          expectedFormat = widget.dateTimeFormat ?? 'yyyy-MM-dd HH:mm';	");
buffer.writeln("	          return 'Invalid date & time format, expected: \$expectedFormat';	");
buffer.writeln("	        }	");
buffer.writeln("	      }	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    if (widget.validators != null) {	");
buffer.writeln("	      for (var validator in widget.validators!) {	");
buffer.writeln("	        final result = validator(value);	");
buffer.writeln("	        if (result != null) return result;	");
buffer.writeln("	      }	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    if (widget.validator != null) {	");
buffer.writeln("	      return widget.validator!(value);	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    return null;	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Widget _buildLabel() {	");
buffer.writeln("	    if (widget.label == null) return const SizedBox.shrink();	");
buffer.writeln("	    	");
buffer.writeln('    final theme = Theme.of(context);');
buffer.writeln('    final TextStyle baseStyle = theme.textTheme.bodyMedium!.copyWith(');
buffer.writeln('      fontWeight: FontWeight.w400,');
buffer.writeln('    );');
buffer.writeln('    final Color requiredMarkColor = theme.colorScheme.error;');
buffer.writeln('');
buffer.writeln("	    return RichText(	");
buffer.writeln("	      text: TextSpan(	");
buffer.writeln("	        text: widget.label!,	");
buffer.writeln('        style: baseStyle,');
buffer.writeln("	        children: widget.isMandatory	");
buffer.writeln("	            ? [	");
buffer.writeln("	                const TextSpan(	");
buffer.writeln("	                  text: ' *',	");
buffer.writeln('                  style: baseStyle.copyWith(color: requiredMarkColor),');
buffer.writeln("	                ),	");
buffer.writeln("	              ]	");
buffer.writeln("	            : [],	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Widget? _buildSuffixIcon() {	");
buffer.writeln("	    if (!widget.enableSuffix) return null;	");
buffer.writeln("		");
buffer.writeln("	    if (widget.showClearButton && _internalController.text.isNotEmpty && _isFocused) {	");
buffer.writeln("	      return IconButton(	");
buffer.writeln("	        icon: const Icon(Icons.clear),	");
buffer.writeln("	        onPressed: _clearText,	");
buffer.writeln("	      );	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    if (widget.suffixIcon != null) {	");
buffer.writeln("	      return IconButton(	");
buffer.writeln("	        icon: Icon(widget.suffixIcon),	");
buffer.writeln("	        onPressed: () {},	");
buffer.writeln("	      );	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    if (widget.isPassword) {	");
buffer.writeln("	      return IconButton(	");
buffer.writeln("	        icon: Icon(obscureText ? Icons.visibility : Icons.visibility_off),	");
buffer.writeln("	        onPressed: _togglePassword,	");
buffer.writeln("	      );	");
buffer.writeln("	    } else if (widget.isDatePicker) {	");
buffer.writeln("	      return IconButton(	");
buffer.writeln("	        icon: const Icon(Icons.calendar_today),	");
buffer.writeln("	        onPressed: _pickDate,	");
buffer.writeln("	      );	");
buffer.writeln("	    } else if (widget.isTimePicker) {	");
buffer.writeln("	      return IconButton(	");
buffer.writeln("	        icon: const Icon(Icons.access_time),	");
buffer.writeln("	        onPressed: _pickTime,	");
buffer.writeln("	      );	");
buffer.writeln("	    } else if (widget.isDateTimePicker) {	");
buffer.writeln("	      return IconButton(	");
buffer.writeln("	        icon: const Icon(Icons.date_range),	");
buffer.writeln("	        onPressed: _pickDateTime,	");
buffer.writeln("	      );	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    return null;	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  Widget build(BuildContext context) {	");
buffer.writeln("	    final theme = Theme.of(context);	");
buffer.writeln("	    final defaultDecoration = InputDecoration(	");
buffer.writeln("	      label: widget.labelPosition == LabelPosition.floating ? _buildLabel() : null,	");
buffer.writeln("	      hintText: widget.hint,	");
buffer.writeln("	      helperText: widget.helperText,	");
buffer.writeln("	      errorText: widget.errorText,	");
buffer.writeln("	      prefixIcon: widget.prefixIcon != null ? Icon(widget.prefixIcon) : null,	");
buffer.writeln("	      suffixIcon: _buildSuffixIcon(),	");
buffer.writeln("	      border: const OutlineInputBorder(),	");
buffer.writeln("	      filled: widget.fillColor != null,	");
buffer.writeln("	      fillColor: widget.fillColor,	");
buffer.writeln("	    ).applyDefaults(theme.inputDecorationTheme).copyWith(	");
buffer.writeln("	      // Apply any custom decoration theme	");
buffer.writeln("	  // Apply custom decoration theme properties directly	");
buffer.writeln("	  alignLabelWithHint: widget.decorationTheme?.alignLabelWithHint,	");
buffer.writeln("	  isDense: widget.decorationTheme?.isDense,	");
buffer.writeln("	  contentPadding: widget.decorationTheme?.contentPadding,	");
buffer.writeln("	  // Add other properties you want to override from decorationTheme	");
buffer.writeln("	    );	");
buffer.writeln("		");
buffer.writeln("	    final textField = Semantics(	");
buffer.writeln("	      label: widget.label,	");
buffer.writeln("	      value: _internalController.text,	");
buffer.writeln("	      child: TextFormField(	");
buffer.writeln("	        controller: _internalController,	");
buffer.writeln("	        focusNode: _internalFocusNode,	");
buffer.writeln("	        obscureText: obscureText,	");
buffer.writeln("	        keyboardType: widget.isNumber ? TextInputType.number : widget.keyboardType,	");
buffer.writeln("	        validator: _combinedValidator,	");
buffer.writeln("	        onSaved: widget.onSaved,	");
buffer.writeln("	        readOnly: widget.readOnly || widget.isDatePicker || widget.isTimePicker || widget.isDateTimePicker,	");
buffer.writeln("	        enabled: widget.enabled,	");
buffer.writeln("	        onChanged: (value) {	");
buffer.writeln("	          widget.onChanged?.call(value);	");
buffer.writeln("	          if (widget.validationMode == ValidationMode.onChanged) {	");
buffer.writeln("	            WidgetsBinding.instance.addPostFrameCallback((_) {	");
buffer.writeln("	              _internalFocusNode.context?.findAncestorStateOfType<FormState>()?.validate();	");
buffer.writeln("	            });	");
buffer.writeln("	          }	");
buffer.writeln("	        },	");
buffer.writeln("	        textInputAction: widget.textInputAction,	");
buffer.writeln("	        textCapitalization: widget.textCapitalization,	");
buffer.writeln("	        inputFormatters: widget.inputFormatters,	");
buffer.writeln("	        maxLines: widget.maxLines,	");
buffer.writeln("	        minLines: widget.minLines,	");
buffer.writeln("	        autovalidateMode: widget.autovalidateMode,	");
buffer.writeln("	        style: widget.textStyle,	");
buffer.writeln("	        decoration: widget.decoration?.copyWith(	");
buffer.writeln("	          label: widget.labelPosition == LabelPosition.floating ? _buildLabel() : null,	");
buffer.writeln("	          suffixIcon: _buildSuffixIcon(),	");
buffer.writeln("	        ) ?? defaultDecoration,	");
buffer.writeln("	        autofocus: widget.autoFocus,	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("		");
buffer.writeln("	    final sizedTextField = widget.width != null || widget.height != null	");
buffer.writeln("	        ? SizedBox(	");
buffer.writeln("	            width: widget.width,	");
buffer.writeln("	            height: widget.height,	");
buffer.writeln("	            child: textField,	");
buffer.writeln("	          )	");
buffer.writeln("	        : textField;	");
buffer.writeln("		");
buffer.writeln("	    final paddedTextField = widget.padding != null	");
buffer.writeln("	        ? Padding(	");
buffer.writeln("	            padding: widget.padding!,	");
buffer.writeln("	            child: sizedTextField,	");
buffer.writeln("	          )	");
buffer.writeln("	        : sizedTextField;	");
buffer.writeln("		");
buffer.writeln("	    if (widget.labelPosition == LabelPosition.floating) return paddedTextField;	");
buffer.writeln("		");
buffer.writeln("	    switch (widget.labelPosition) {	");
buffer.writeln("	      case LabelPosition.top:	");
buffer.writeln("	        return Column(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            _buildLabel(),	");
buffer.writeln("	            const SizedBox(height: 8),	");
buffer.writeln("	            paddedTextField,	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	      case LabelPosition.left:	");
buffer.writeln("	        return Row(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            SizedBox(	");
buffer.writeln("	              width: 100,	");
buffer.writeln("	              child: Padding(	");
buffer.writeln("	                padding: const EdgeInsets.only(top: 16),	");
buffer.writeln("	                child: _buildLabel(),	");
buffer.writeln("	              ),	");
buffer.writeln("	            ),	");
buffer.writeln("	            const SizedBox(width: 10),	");
buffer.writeln("	            Expanded(child: paddedTextField),	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	      case LabelPosition.inline:	");
buffer.writeln("	        return Row(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.center,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            _buildLabel(),	");
buffer.writeln("	            const SizedBox(width: 10),	");
buffer.writeln("	            Expanded(child: paddedTextField),	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	      default:	");
buffer.writeln("	        return paddedTextField;	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("	}	");
  return buffer.toString().replaceAll('\u00A0', ' ');
}
