import 'journey_field.dart';
import 'model_parsers.dart';

class InputComponent extends JourneyField {
  InputComponent({
    required super.id,
    required super.label,
    required super.type,
    super.required,
    super.visible,
    super.readOnly,
    super.placeholder,
    super.hintText,
    super.errorMessage,
    super.disable,
    super.hidden,
    super.visibleIf,
    super.conditionalValidations,
    super.asyncValidation,
    super.validationPattern,
    super.dependsOn,
    super.visibleForRoles,
    super.editableForRoles,
    
    super.groupId,
    super.sectionId,
    super.expression,
    super.defaultValueExpression,
    super.cascadeConfig,
    super.localization,
    super.defaultValue,
    super.fieldtype,
    super.maxLength,
    super.minLength,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.obscureText,
    super.autocorrect,
    super.enableSuggestions,
    super.formula,
  });

  factory InputComponent.fromJson(Map<String, dynamic> json) {
    return InputComponent(
      id: json['id'] ?? '',
      label: json['label'] ?? '',
      type: json['type'] ?? 'text',
      required: json['required'] ?? false,
      visible: json['visible'] ?? true,
      readOnly: json['readOnly'] ?? false,
      placeholder: json['placeholder'],
      hintText: json['hintText'],
      errorMessage: json['errorMessage'],
      disable: json['disable'] ?? false,
      hidden: json['hidden'] ?? false,
      visibleIf: json['visibleIf'],
      conditionalValidations: parseMapList(json['conditionalValidations']),
      asyncValidation: json['asyncValidation'],
      validationPattern: json['validationPattern'],
      dependsOn: json['dependsOn'],
      visibleForRoles: parseStringList(json['visibleForRoles']),
      editableForRoles: parseStringList(json['editableForRoles']),
      
      defaultValue: json['defaultValue']?.toString() ?? json['initialValue']?.toString(),
      groupId: json['groupId'],
      sectionId: json['sectionId'],
      expression: json['expression'],
      defaultValueExpression: json['defaultValueExpression'],
      cascadeConfig: json['cascadeConfig'],
      localization: json['localization'],
      fieldtype: json['fieldtype'],
      maxLength: parseInt(json['maxLength']),
      minLength: parseInt(json['minLength']),
      keyboardType: json['keyboardType'],
      textInputAction: json['textInputAction'],
      textCapitalization: json['textCapitalization'],
      obscureText: json['obscureText'] ?? false,
      autocorrect: json['autocorrect'] ?? true,
      enableSuggestions: json['enableSuggestions'] ?? true,
      formula: json['formula'],
    );
  }
}

class OptionsComponent extends JourneyField {
  OptionsComponent({
    required super.id,
    required super.label,
    required super.type,
    super.required,
    super.visible,
    super.readOnly,
    super.placeholder,
    super.hintText,
    super.errorMessage,
    super.disable,
    super.hidden,
    super.visibleIf,
    super.conditionalValidations,
    super.asyncValidation,
    super.validationPattern,
    super.dependsOn,
    super.visibleForRoles,
    super.editableForRoles,
    
    super.groupId,
    super.sectionId,
    super.expression,
    super.defaultValueExpression,
    super.cascadeConfig,
    super.localization,
    super.options,
    super.useStaticOptions,
    super.staticOptions,
    super.dropdownApiUrl,
    super.dropdownApiMethod,
    super.dropdownApiHeaders,
    super.dropdownApiBody,
    super.dropdownkey,
    super.dropdownValue,
    super.dropdowndata,
    super.dropdownApiResponseKey,
    super.dropdownListKey,
    super.apiParam,
    super.defaultValue,
  });

  factory OptionsComponent.fromJson(Map<String, dynamic> json) {
    return OptionsComponent(
      id: json['id'] ?? '',
      label: json['label'] ?? '',
      type: json['type'] ?? 'dropdown',
      required: json['required'] ?? false,
      visible: json['visible'] ?? true,
      readOnly: json['readOnly'] ?? false,
      placeholder: json['placeholder'],
      hintText: json['hintText'],
      errorMessage: json['errorMessage'],
      disable: json['disable'] ?? false,
      hidden: json['hidden'] ?? false,
      visibleIf: json['visibleIf'],
      conditionalValidations: parseMapList(json['conditionalValidations']),
      asyncValidation: json['asyncValidation'],
      validationPattern: json['validationPattern'],
      dependsOn: json['dependsOn'],
      visibleForRoles: parseStringList(json['visibleForRoles']),
      editableForRoles: parseStringList(json['editableForRoles']),
      
      options: parseStringList(json['options']),
      useStaticOptions: json['useStaticOptions'] ?? false,
      staticOptions: parseStringMapList(json['staticOptions']),
      dropdownApiUrl: json['dropdownApiUrl'] ?? json['apiUrl'],
      dropdownApiMethod: json['dropdownApiMethod'],
      dropdownApiHeaders: json['dropdownApiHeaders'],
      dropdownApiBody: json['dropdownApiBody'],
      dropdownkey: json['dropdownkey'] ?? json['dropdownKey'] ?? json['dropdownValueKey'],
      dropdownValue: json['dropdownValue'] ?? json['dropdownLabelKey'],
      dropdowndata: json['dropdowndata'] is List ? List.from(json['dropdowndata']) : json['dropdowndata'],
      dropdownApiResponseKey: json['dropdownApiResponseKey'] ?? json['responseListKey'],
      dropdownListKey: json['dropdownListKey'],
      apiParam: json['apiParam'],
      defaultValue: json['defaultValue']?.toString(),
    );
  }
}

class LayoutComponent extends JourneyField {
  LayoutComponent({
    required super.id,
    required super.label,
    required super.type,
    super.required,
    super.visible,
    super.readOnly,
    super.placeholder,
    super.hintText,
    super.errorMessage,
    super.disable,
    super.hidden,
    super.visibleIf,
    super.conditionalValidations,
    super.asyncValidation,
    super.validationPattern,
    super.dependsOn,
    super.visibleForRoles,
    super.editableForRoles,
    
    super.nestedFields,
    super.componentConfig,
  });

  factory LayoutComponent.fromJson(Map<String, dynamic> json) {
    return LayoutComponent(
      id: json['id'] ?? '',
      label: json['label'] ?? '',
      type: json['type'] ?? 'section',
      required: json['required'] ?? false,
      visible: json['visible'] ?? true,
      readOnly: json['readOnly'] ?? false,
      placeholder: json['placeholder'],
      hintText: json['hintText'],
      errorMessage: json['errorMessage'],
      disable: json['disable'] ?? false,
      hidden: json['hidden'] ?? false,
      visibleIf: json['visibleIf'],
      conditionalValidations: parseMapList(json['conditionalValidations']),
      asyncValidation: json['asyncValidation'],
      validationPattern: json['validationPattern'],
      dependsOn: json['dependsOn'],
      visibleForRoles: parseStringList(json['visibleForRoles']),
      editableForRoles: parseStringList(json['editableForRoles']),
      
      nestedFields: parseNestedFields(json['nestedFields'] ?? json['children'] ?? json['fields']),
      componentConfig: json['componentConfig'],
    );
  }
}

class GridComponent extends JourneyField {
  GridComponent({
    required super.id,
    required super.label,
    required super.type,
    super.required,
    super.visible,
    super.readOnly,
    super.placeholder,
    super.hintText,
    super.errorMessage,
    super.disable,
    super.hidden,
    super.visibleIf,
    super.conditionalValidations,
    super.asyncValidation,
    super.validationPattern,
    super.dependsOn,
    super.visibleForRoles,
    super.editableForRoles,
    
    super.nestedFields,
    super.componentConfig,
  });

  factory GridComponent.fromJson(Map<String, dynamic> json) {
    return GridComponent(
      id: json['id'] ?? '',
      label: json['label'] ?? '',
      type: json['type'] ?? 'table_grid',
      required: json['required'] ?? false,
      visible: json['visible'] ?? true,
      readOnly: json['readOnly'] ?? false,
      placeholder: json['placeholder'],
      hintText: json['hintText'],
      errorMessage: json['errorMessage'],
      disable: json['disable'] ?? false,
      hidden: json['hidden'] ?? false,
      visibleIf: json['visibleIf'],
      conditionalValidations: parseMapList(json['conditionalValidations']),
      asyncValidation: json['asyncValidation'],
      validationPattern: json['validationPattern'],
      dependsOn: json['dependsOn'],
      visibleForRoles: parseStringList(json['visibleForRoles']),
      editableForRoles: parseStringList(json['editableForRoles']),
      
      nestedFields: parseNestedFields(json['nestedFields'] ?? json['children'] ?? json['fields']),
      componentConfig: json['componentConfig'],
    );
  }
}

class RepeaterComponent extends JourneyField {
  RepeaterComponent({
    required super.id,
    required super.label,
    required super.type,
    super.required,
    super.visible,
    super.readOnly,
    super.placeholder,
    super.hintText,
    super.errorMessage,
    super.disable,
    super.hidden,
    super.visibleIf,
    super.conditionalValidations,
    super.asyncValidation,
    super.validationPattern,
    super.dependsOn,
    super.visibleForRoles,
    super.editableForRoles,
    
    super.groupId,
    super.sectionId,
    super.expression,
    super.defaultValueExpression,
    super.cascadeConfig,
    super.localization,
    super.nestedFields,
    super.repeatableGroup,
    super.repeatConfig,
  });

  factory RepeaterComponent.fromJson(Map<String, dynamic> json) {
    return RepeaterComponent(
      id: json['id'] ?? '',
      label: json['label'] ?? '',
      type: json['type'] ?? 'repeater',
      required: json['required'] ?? false,
      visible: json['visible'] ?? true,
      readOnly: json['readOnly'] ?? false,
      placeholder: json['placeholder'],
      hintText: json['hintText'],
      errorMessage: json['errorMessage'],
      disable: json['disable'] ?? false,
      hidden: json['hidden'] ?? false,
      visibleIf: json['visibleIf'],
      conditionalValidations: parseMapList(json['conditionalValidations']),
      asyncValidation: json['asyncValidation'],
      validationPattern: json['validationPattern'],
      dependsOn: json['dependsOn'],
      visibleForRoles: parseStringList(json['visibleForRoles']),
      editableForRoles: parseStringList(json['editableForRoles']),
      
      nestedFields: parseNestedFields(json['nestedFields'] ?? json['children'] ?? json['fields']),
      repeatableGroup: json['repeatableGroup'] ?? true,
      repeatConfig: json['repeatConfig'],
      groupId: json['groupId'],
      sectionId: json['sectionId'],
      expression: json['expression'],
      defaultValueExpression: json['defaultValueExpression'],
      cascadeConfig: json['cascadeConfig'],
      localization: json['localization'],
    );
  }
}
