import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateAccordionLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF0F0FF),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              SingleChildScrollView(");
  buffer.writeln("                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),");
  buffer.writeln("                child: Center(");
  buffer.writeln("                  child: ConstrainedBox(");
  buffer.writeln("                    constraints: const BoxConstraints(maxWidth: 800),");
  buffer.writeln("                    child: Column(");
  buffer.writeln("                      children: List.generate(total > 0 ? total : 1, (index) {");
  buffer.writeln("                        if (total == 0) {");
  buffer.writeln("                          return Container(");
  buffer.writeln("                            padding: const EdgeInsets.all(16),");
  buffer.writeln("                            child: _buildFormContent(context),");
  buffer.writeln("                          );");
  buffer.writeln("                        }");
  buffer.writeln("                        final isCompleted = index < activeIdx;");
  buffer.writeln("                        final isActive = index == activeIdx;");
  buffer.writeln("                        return Container(");
  buffer.writeln("                          margin: const EdgeInsets.only(bottom: 12),");
  buffer.writeln("                          decoration: BoxDecoration(");
  buffer.writeln("                            color: Colors.white,");
  buffer.writeln("                            borderRadius: BorderRadius.circular(16),");
  buffer.writeln("                            border: Border.all(");
  buffer.writeln("                              color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFFE4E6F0),");
  buffer.writeln("                              width: isActive ? 1.5 : 1.0,");
  buffer.writeln("                            ),");
  buffer.writeln("                            boxShadow: const [");
  buffer.writeln("                              BoxShadow(");
  buffer.writeln("                                color: Color(0x04000000),");
  buffer.writeln("                                blurRadius: 10,");
  buffer.writeln("                                offset: Offset(0, 4),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                          child: Column(");
  buffer.writeln("                            children: [");
  buffer.writeln("                              InkWell(");
  buffer.writeln("                                onTap: (isCompleted || isActive)");
  buffer.writeln("                                    ? () => Get.toNamed('/' + _getStepId(index))");
  buffer.writeln("                                    : null,");
  buffer.writeln("                                child: Padding(");
  buffer.writeln("                                  padding: const EdgeInsets.all(16),");
  buffer.writeln("                                  child: Row(");
  buffer.writeln("                                    children: [");
  buffer.writeln("                                      Container(");
  buffer.writeln("                                        width: 28,");
  buffer.writeln("                                        height: 28,");
  buffer.writeln("                                        decoration: BoxDecoration(");
  buffer.writeln("                                          color: isActive");
  buffer.writeln("                                              ? const Color(0xFFEEECFD)");
  buffer.writeln("                                              : isCompleted");
  buffer.writeln("                                                  ? const Color(0xFFE8F9EE)");
  buffer.writeln("                                                  : const Color(0xFFFAFAFF),");
  buffer.writeln("                                          shape: BoxShape.circle,");
  buffer.writeln("                                        ),");
  buffer.writeln("                                        child: Center(");
  buffer.writeln("                                          child: isCompleted");
  buffer.writeln("                                              ? const Icon(Icons.check_rounded, color: Color(0xFF22C55E), size: 14)");
  buffer.writeln("                                              : Text(");
  buffer.writeln("                                                  '\${index + 1}',");
  buffer.writeln("                                                  style: GoogleFonts.poppins(");
  buffer.writeln("                                                    color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFF6B7280),");
  buffer.writeln("                                                    fontWeight: isActive ? FontWeight.bold : FontWeight.normal,");
  buffer.writeln("                                                    fontSize: 14,");
  buffer.writeln("                                                  ),");
  buffer.writeln("                                                ),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      const SizedBox(width: 14),");
  buffer.writeln("                                      Expanded(");
  buffer.writeln("                                        child: Column(");
  buffer.writeln("                                          crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                          children: [");
  buffer.writeln("                                            Text(");
  buffer.writeln("                                              _getStepTitle(index),");
  buffer.writeln("                                              style: GoogleFonts.poppins(");
  buffer.writeln("                                                fontSize: 16,");
  buffer.writeln("                                                fontWeight: isActive ? FontWeight.bold : FontWeight.w500,");
  buffer.writeln("                                                color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFF1A1A2E),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                            ),");
  buffer.writeln("                                            Text(");
  buffer.writeln("                                              _getStepDesc(index),");
  buffer.writeln("                                              style: GoogleFonts.poppins(");
  buffer.writeln("                                                fontSize: 13,");
  buffer.writeln("                                                color: const Color(0xFF6B7280),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                              maxLines: 1,");
  buffer.writeln("                                              overflow: TextOverflow.ellipsis,");
  buffer.writeln("                                            ),");
  buffer.writeln("                                          ],");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      Icon(");
  buffer.writeln("                                        isActive ? Icons.expand_less_rounded : Icons.expand_more_rounded,");
  buffer.writeln("                                        color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFF6B7280),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                              if (isActive) ...[");
  buffer.writeln("                                const Padding(");
  buffer.writeln("                                  padding: EdgeInsets.symmetric(horizontal: 16),");
  buffer.writeln("                                  child: Divider(height: 1, color: Color(0xFFE4E6F0)),");
  buffer.writeln("                                ),");
  buffer.writeln("                                Padding(");
  buffer.writeln("                                  padding: const EdgeInsets.all(16),");
  buffer.writeln("                                  child: _buildFormContent(context),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ],");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                        );");
  buffer.writeln("                      }),");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("              ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
