import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateChatLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 640;");
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln();
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF7F6FB),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              ListView(");
  buffer.writeln("                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),");
  buffer.writeln("                children: [");
  buffer.writeln("                  // System message");
  buffer.writeln("                  _buildSystemMessage('Welcome! I will guide you step-by-step. Let\'s get started.'),");
  buffer.writeln("                  const SizedBox(height: 20),");
  buffer.writeln("                  ");
  buffer.writeln("                  // Chat history");
  buffer.writeln("                  ...List.generate(activeIdx, (idx) {");
  buffer.writeln("                    final title = _getStepTitle(idx);");
  buffer.writeln("                    return Column(");
  buffer.writeln("                      children: [");
  buffer.writeln("                        _buildBotPrompt('First, please complete the **\$title** section.', title),");
  buffer.writeln("                        const SizedBox(height: 12),");
  buffer.writeln("                        _buildUserResponseSummary(title, idx),");
  buffer.writeln("                        const SizedBox(height: 20),");
  buffer.writeln("                      ],");
  buffer.writeln("                    );");
  buffer.writeln("                  }),");
  buffer.writeln("                  ");
  buffer.writeln("                  // Active bot prompt");
  buffer.writeln("                  _buildBotPrompt(");
  buffer.writeln("                    'Great! Now, let\'s fill in the **${stepMeta.escapedTitle}** details below:',");
  buffer.writeln("                    '${stepMeta.escapedTitle}',");
  buffer.writeln("                  ),");
  buffer.writeln("                  const SizedBox(height: 12),");
  buffer.writeln("                  ");
  buffer.writeln("                  // Active Form bubble");
  buffer.writeln("                  _buildActiveFormBubble(context, isMobile),");
  buffer.writeln("                  const SizedBox(height: 30),");
  buffer.writeln("                ],");
  buffer.writeln("              ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}

void generateChatHelpers(StringBuffer buffer) {
  buffer.writeln("  Widget _buildSystemMessage(String text) {");
  buffer.writeln("    return Center(");
  buffer.writeln("      child: Container(");
  buffer.writeln("        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),");
  buffer.writeln("        decoration: BoxDecoration(");
  buffer.writeln("          color: Colors.white,");
  buffer.writeln("          borderRadius: BorderRadius.circular(12),");
  buffer.writeln("          border: Border.all(color: const Color(0xFFE4E6F0), width: 0.8),");
  buffer.writeln("        ),");
  buffer.writeln("        child: Text(");
  buffer.writeln("          text,");
  buffer.writeln("          textAlign: TextAlign.center,");
  buffer.writeln("          style: GoogleFonts.poppins(");
  buffer.writeln("            fontSize: 11,");
  buffer.writeln("            color: const Color(0xFF6B7280),");
  buffer.writeln("            fontWeight: FontWeight.w500,");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildBotPrompt(String prompt, String title) {");
  buffer.writeln("    return Row(");
  buffer.writeln("      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("      children: [");
  buffer.writeln("        Container(");
  buffer.writeln("          width: 32,");
  buffer.writeln("          height: 32,");
  buffer.writeln("          decoration: const BoxDecoration(");
  buffer.writeln("            color: Color(0xFF5B4FCF),");
  buffer.writeln("            shape: BoxShape.circle,");
  buffer.writeln("          ),");
  buffer.writeln("          child: const Icon(Icons.support_agent_rounded, color: Colors.white, size: 16),");
  buffer.writeln("        ),");
  buffer.writeln("        const SizedBox(width: 10),");
  buffer.writeln("        Flexible(");
  buffer.writeln("          child: Container(");
  buffer.writeln("            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),");
  buffer.writeln("            decoration: const BoxDecoration(");
  buffer.writeln("              color: Colors.white,");
  buffer.writeln("              borderRadius: BorderRadius.only(");
  buffer.writeln("                topRight: Radius.circular(16),");
  buffer.writeln("                bottomLeft: Radius.circular(16),");
  buffer.writeln("                bottomRight: Radius.circular(16),");
  buffer.writeln("              ),");
  buffer.writeln("              boxShadow: [");
  buffer.writeln("                BoxShadow(");
  buffer.writeln("                  color: Color(0x05000000),");
  buffer.writeln("                  blurRadius: 10,");
  buffer.writeln("                  offset: Offset(0, 2),");
  buffer.writeln("                ),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("            child: Column(");
  buffer.writeln("              crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("              children: [");
  buffer.writeln("                Text(");
  buffer.writeln("                  'RevoBot',");
  buffer.writeln("                  style: GoogleFonts.poppins(");
  buffer.writeln("                    fontSize: 10,");
  buffer.writeln("                    fontWeight: FontWeight.bold,");
  buffer.writeln("                    color: const Color(0xFF5B4FCF),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("                const SizedBox(height: 4),");
  buffer.writeln("                Text(");
  buffer.writeln("                  prompt,");
  buffer.writeln("                  style: GoogleFonts.poppins(");
  buffer.writeln("                    fontSize: 13,");
  buffer.writeln("                    color: const Color(0xFF1A1A2E),");
  buffer.writeln("                    height: 1.4,");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ],");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildUserResponseSummary(String title, int idx) {");
  buffer.writeln("    return Row(");
  buffer.writeln("      mainAxisAlignment: MainAxisAlignment.end,");
  buffer.writeln("      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("      children: [");
  buffer.writeln("        Flexible(");
  buffer.writeln("          child: Container(");
  buffer.writeln("            margin: const EdgeInsets.only(left: 48),");
  buffer.writeln("            padding: const EdgeInsets.all(16),");
  buffer.writeln("            decoration: BoxDecoration(");
  buffer.writeln("              color: const Color(0xFFEEECFD),");
  buffer.writeln("              borderRadius: const BorderRadius.only(");
  buffer.writeln("                topLeft: Radius.circular(16),");
  buffer.writeln("                bottomLeft: Radius.circular(16),");
  buffer.writeln("                bottomRight: Radius.circular(16),");
  buffer.writeln("              ),");
  buffer.writeln("              border: Border.all(color: const Color(0xFF5B4FCF).withValues(alpha: 0.1)),");
  buffer.writeln("            ),");
  buffer.writeln("            child: Column(");
  buffer.writeln("              crossAxisAlignment: CrossAxisAlignment.end,");
  buffer.writeln("              children: [");
  buffer.writeln("                Row(");
  buffer.writeln("                  mainAxisSize: MainAxisSize.min,");
  buffer.writeln("                  children: [");
  buffer.writeln("                    const Icon(Icons.check_circle_rounded, color: Color(0xFF22C55E), size: 14),");
  buffer.writeln("                    const SizedBox(width: 6),");
  buffer.writeln("                    Text(");
  buffer.writeln("                      'Completed \$title',");
  buffer.writeln("                      style: GoogleFonts.poppins(");
  buffer.writeln("                        fontSize: 11,");
  buffer.writeln("                        fontWeight: FontWeight.bold,");
  buffer.writeln("                        color: const Color(0xFF5B4FCF),");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("                  ],");
  buffer.writeln("                ),");
  buffer.writeln("                const SizedBox(height: 8),");
  buffer.writeln("                GestureDetector(");
  buffer.writeln("                  onTap: () => Get.toNamed('/' + _getStepId(idx)),");
  buffer.writeln("                  child: Text(");
  buffer.writeln("                    'Edit Section',");
  buffer.writeln("                    style: GoogleFonts.poppins(");
  buffer.writeln("                      fontSize: 11,");
  buffer.writeln("                      fontWeight: FontWeight.bold,");
  buffer.writeln("                      color: const Color(0xFF5B4FCF),");
  buffer.writeln("                      decoration: TextDecoration.underline,");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("        const SizedBox(width: 8),");
  buffer.writeln("        Container(");
  buffer.writeln("          width: 32,");
  buffer.writeln("          height: 32,");
  buffer.writeln("          decoration: BoxDecoration(");
  buffer.writeln("            color: const Color(0xFF5B4FCF).withValues(alpha: 0.1),");
  buffer.writeln("            shape: BoxShape.circle,");
  buffer.writeln("          ),");
  buffer.writeln("          child: const Icon(Icons.person_rounded, color: Color(0xFF5B4FCF), size: 16),");
  buffer.writeln("        ),");
  buffer.writeln("      ],");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildActiveFormBubble(BuildContext context, bool isMobile) {");
  buffer.writeln("    return Row(");
  buffer.writeln("      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("      children: [");
  buffer.writeln("        const SizedBox(width: 42),");
  buffer.writeln("        Expanded(");
  buffer.writeln("          child: Container(");
  buffer.writeln("            padding: const EdgeInsets.all(20),");
  buffer.writeln("            decoration: BoxDecoration(");
  buffer.writeln("              color: Colors.white,");
  buffer.writeln("              borderRadius: BorderRadius.circular(20),");
  buffer.writeln("              border: Border.all(color: const Color(0xFF5B4FCF), width: 1.5),");
  buffer.writeln("              boxShadow: [");
  buffer.writeln("                BoxShadow(");
  buffer.writeln("                  color: const Color(0xFF5B4FCF).withValues(alpha: 0.05),");
  buffer.writeln("                  blurRadius: 20,");
  buffer.writeln("                  offset: const Offset(0, 4),");
  buffer.writeln("                ),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("            child: _buildFormContent(context, isMobile: isMobile),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ],");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();
}
