import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateDashboardLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final screenW = MediaQuery.of(context).size.width;");
  buffer.writeln("    final isMobile = screenW < 760;");
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    final progressVal = total > 0 ? (activeIdx / total) : 0.0;");
  buffer.writeln("    final crossAxisCount = screenW > 960 ? 3 : (screenW > 640 ? 2 : 1);");
  buffer.writeln();
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF8F9FD),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              SingleChildScrollView(");
  buffer.writeln("                padding: EdgeInsets.symmetric(");
  buffer.writeln("                  horizontal: isMobile ? 16 : 24,");
  buffer.writeln("                  vertical: 20,");
  buffer.writeln("                ),");
  buffer.writeln("                child: Center(");
  buffer.writeln("                  child: ConstrainedBox(");
  buffer.writeln("                    constraints: const BoxConstraints(maxWidth: 1100),");
  buffer.writeln("                    child: Column(");
  buffer.writeln("                      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                      children: [");
  buffer.writeln("                        // Dashboard Header Stats");
  buffer.writeln("                        Container(");
  buffer.writeln("                          width: double.infinity,");
  buffer.writeln("                          padding: const EdgeInsets.all(24),");
  buffer.writeln("                          decoration: BoxDecoration(");
  buffer.writeln("                            color: Colors.white,");
  buffer.writeln("                            borderRadius: BorderRadius.circular(24),");
  buffer.writeln("                            border: Border.all(color: const Color(0xFFE4E6F0), width: 1.2),");
  buffer.writeln("                            boxShadow: [");
  buffer.writeln("                              BoxShadow(");
  buffer.writeln("                                color: const Color(0xFF5B4FCF).withValues(alpha: 0.04),");
  buffer.writeln("                                blurRadius: 24,");
  buffer.writeln("                                offset: const Offset(0, 4),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                          child: isMobile");
  buffer.writeln("                              ? Column(");
  buffer.writeln("                                  crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                  children: [");
  buffer.writeln("                                    _buildSummaryStats(activeIdx, total),");
  buffer.writeln("                                    const SizedBox(height: 16),");
  buffer.writeln("                                    _buildProgressBar(progressVal),");
  buffer.writeln("                                  ],");
  buffer.writeln("                                )");
  buffer.writeln("                              : Row(");
  buffer.writeln("                                  children: [");
  buffer.writeln("                                    Expanded(child: _buildSummaryStats(activeIdx, total)),");
  buffer.writeln("                                    const SizedBox(width: 40),");
  buffer.writeln("                                    Expanded(child: _buildProgressBar(progressVal)),");
  buffer.writeln("                                  ],");
  buffer.writeln("                                ),");
  buffer.writeln("                        ),");
  buffer.writeln("                        const SizedBox(height: 28),");
  buffer.writeln("                        ");
  buffer.writeln("                        // Main split content");
  buffer.writeln("                        if (isMobile) ...[");
  buffer.writeln("                          // Active Card");
  buffer.writeln("                          _buildActiveFormCard(context, isMobile: true),");
  buffer.writeln("                          const SizedBox(height: 28),");
  buffer.writeln("                          _buildGridSection(context, total, activeIdx, crossAxisCount),");
  buffer.writeln("                        ] else");
  buffer.writeln("                          Row(");
  buffer.writeln("                            crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                            children: [");
  buffer.writeln("                              Expanded(");
  buffer.writeln("                                flex: 6,");
  buffer.writeln("                                child: _buildActiveFormCard(context, isMobile: false),");
  buffer.writeln("                              ),");
  buffer.writeln("                              const SizedBox(width: 24),");
  buffer.writeln("                              Expanded(");
  buffer.writeln("                                flex: 4,");
  buffer.writeln("                                child: Column(");
  buffer.writeln("                                  crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                  children: [");
  buffer.writeln("                                    Text(");
  buffer.writeln("                                      'Journey Sections',");
  buffer.writeln("                                      style: GoogleFonts.poppins(");
  buffer.writeln("                                        fontSize: 16,");
  buffer.writeln("                                        fontWeight: FontWeight.bold,");
  buffer.writeln("                                        color: const Color(0xFF1A1A2E),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                    const SizedBox(height: 16),");
  buffer.writeln("                                    ...List.generate(total, (idx) {");
  buffer.writeln("                                      final stepTitle = _getStepTitle(idx);");
  buffer.writeln("                                      final isCompleted = idx < activeIdx;");
  buffer.writeln("                                      final isActive = idx == activeIdx;");
  buffer.writeln("                                      return _buildMiniStepCard(stepTitle, idx, isCompleted, isActive);");
  buffer.writeln("                                    }),");
  buffer.writeln("                                  ],");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                      ],");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("              ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}

void generateDashboardHelpers(StringBuffer buffer) {
  buffer.writeln("  Widget _buildSummaryStats(int completed, int total) {");
  buffer.writeln("    return Column(");
  buffer.writeln("      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("      children: [");
  buffer.writeln("        Text(");
  buffer.writeln("          'Overall Completion Progress',");
  buffer.writeln("          style: GoogleFonts.poppins(");
  buffer.writeln("            fontSize: 12,");
  buffer.writeln("            fontWeight: FontWeight.w600,");
  buffer.writeln("            color: const Color(0xFF6B7280),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("        const SizedBox(height: 6),");
  buffer.writeln("        Text(");
  buffer.writeln("          '\$completed of \$total Tasks Finished',");
  buffer.writeln("          style: GoogleFonts.poppins(");
  buffer.writeln("            fontSize: 22,");
  buffer.writeln("            fontWeight: FontWeight.bold,");
  buffer.writeln("            color: const Color(0xFF1A1A2E),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ],");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildProgressBar(double progress) {");
  buffer.writeln("    return Column(");
  buffer.writeln("      crossAxisAlignment: CrossAxisAlignment.end,");
  buffer.writeln("      children: [");
  buffer.writeln("        Text(");
  buffer.writeln("          '\${(progress * 100).toStringAsFixed(0)}% Done',");
  buffer.writeln("          style: GoogleFonts.poppins(");
  buffer.writeln("            fontSize: 13,");
  buffer.writeln("            fontWeight: FontWeight.bold,");
  buffer.writeln("            color: const Color(0xFF5B4FCF),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("        const SizedBox(height: 8),");
  buffer.writeln("        ClipRRect(");
  buffer.writeln("          borderRadius: BorderRadius.circular(8),");
  buffer.writeln("          child: LinearProgressIndicator(");
  buffer.writeln("            value: progress,");
  buffer.writeln("            minHeight: 8,");
  buffer.writeln("            backgroundColor: const Color(0xFFF0F0FF),");
  buffer.writeln("            valueColor: const AlwaysStoppedAnimation<Color>(Color(0xFF5B4FCF)),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ],");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildActiveFormCard(BuildContext context, {required bool isMobile}) {");
  buffer.writeln("    return Container(");
  buffer.writeln("      padding: EdgeInsets.all(isMobile ? 18 : 28),");
  buffer.writeln("      decoration: BoxDecoration(");
  buffer.writeln("        color: Colors.white,");
  buffer.writeln("        borderRadius: BorderRadius.circular(24),");
  buffer.writeln("        border: Border.all(color: const Color(0xFFE4E6F0), width: 1.2),");
  buffer.writeln("        boxShadow: [");
  buffer.writeln("          BoxShadow(");
  buffer.writeln("            color: const Color(0xFF5B4FCF).withValues(alpha: 0.04),");
  buffer.writeln("            blurRadius: 24,");
  buffer.writeln("            offset: const Offset(0, 4),");
  buffer.writeln("          ),");
  buffer.writeln("        ],");
  buffer.writeln("      ),");
  buffer.writeln("      child: _buildFormContent(context, isMobile: isMobile),");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildGridSection(BuildContext context, int total, int activeIdx, int crossAxisCount) {");
  buffer.writeln("    return Column(");
  buffer.writeln("      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("      children: [");
  buffer.writeln("        Text(");
  buffer.writeln("          'Journey Sections',");
  buffer.writeln("          style: GoogleFonts.poppins(");
  buffer.writeln("            fontSize: 16,");
  buffer.writeln("            fontWeight: FontWeight.bold,");
  buffer.writeln("            color: const Color(0xFF1A1A2E),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("        const SizedBox(height: 16),");
  buffer.writeln("        GridView.builder(");
  buffer.writeln("          shrinkWrap: true,");
  buffer.writeln("          physics: const NeverScrollableScrollPhysics(),");
  buffer.writeln("          itemCount: total,");
  buffer.writeln("          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(");
  buffer.writeln("            crossAxisCount: crossAxisCount,");
  buffer.writeln("            crossAxisSpacing: 16,");
  buffer.writeln("            mainAxisSpacing: 16,");
  buffer.writeln("            mainAxisExtent: 130,");
  buffer.writeln("          ),");
  buffer.writeln("          itemBuilder: (context, idx) {");
  buffer.writeln("            final stepTitle = _getStepTitle(idx);");
  buffer.writeln("            final isCompleted = idx < activeIdx;");
  buffer.writeln("            final isActive = idx == activeIdx;");
  buffer.writeln("            return _buildMiniStepCard(stepTitle, idx, isCompleted, isActive);");
  buffer.writeln("          },");
  buffer.writeln("        ),");
  buffer.writeln("      ],");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();

  buffer.writeln("  Widget _buildMiniStepCard(String title, int idx, bool isCompleted, bool isActive) {");
  buffer.writeln("    Color cardBorder = const Color(0xFFE4E6F0);");
  buffer.writeln("    Color iconBg = const Color(0xFFF0F0FF);");
  buffer.writeln("    Color iconColor = const Color(0xFF6B7280);");
  buffer.writeln("    IconData statusIcon = Icons.lock_rounded;");
  buffer.writeln("    String statusText = 'Locked';");
  buffer.writeln();
  buffer.writeln("    if (isCompleted) {");
  buffer.writeln("      cardBorder = const Color(0xFF22C55E).withValues(alpha: 0.5);");
  buffer.writeln("      iconBg = const Color(0xFFE8F9EE);");
  buffer.writeln("      iconColor = const Color(0xFF22C55E);");
  buffer.writeln("      statusIcon = Icons.check_circle_rounded;");
  buffer.writeln("      statusText = 'Completed';");
  buffer.writeln("    } else if (isActive) {");
  buffer.writeln("      cardBorder = const Color(0xFF5B4FCF);");
  buffer.writeln("      iconBg = const Color(0xFFEEECFD);");
  buffer.writeln("      iconColor = const Color(0xFF5B4FCF);");
  buffer.writeln("      statusIcon = Icons.pending_rounded;");
  buffer.writeln("      statusText = 'Active';");
  buffer.writeln("    }");
  buffer.writeln();
  buffer.writeln("    return Container(");
  buffer.writeln("      margin: const EdgeInsets.only(bottom: 12),");
  buffer.writeln("      padding: const EdgeInsets.all(16),");
  buffer.writeln("      decoration: BoxDecoration(");
  buffer.writeln("        color: Colors.white,");
  buffer.writeln("        borderRadius: BorderRadius.circular(16),");
  buffer.writeln("        border: Border.all(color: cardBorder, width: isActive ? 1.5 : 1),");
  buffer.writeln("      ),");
  buffer.writeln("      child: Row(");
  buffer.writeln("        children: [");
  buffer.writeln("          Container(");
  buffer.writeln("            width: 38,");
  buffer.writeln("            height: 38,");
  buffer.writeln("            decoration: BoxDecoration(");
  buffer.writeln("              color: iconBg,");
  buffer.writeln("              shape: BoxShape.circle,");
  buffer.writeln("            ),");
  buffer.writeln("            child: Icon(_stepIconForTitle(title), color: iconColor, size: 18),");
  buffer.writeln("          ),");
  buffer.writeln("          const SizedBox(width: 12),");
  buffer.writeln("          Expanded(");
  buffer.writeln("            child: Column(");
  buffer.writeln("              crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("              mainAxisAlignment: MainAxisAlignment.center,");
  buffer.writeln("              children: [");
  buffer.writeln("                Text(");
  buffer.writeln("                  title,");
  buffer.writeln("                  overflow: TextOverflow.ellipsis,");
  buffer.writeln("                  style: GoogleFonts.poppins(");
  buffer.writeln("                    fontSize: 13,");
  buffer.writeln("                    fontWeight: FontWeight.bold,");
  buffer.writeln("                    color: const Color(0xFF1A1A2E),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("                const SizedBox(height: 2),");
  buffer.writeln("                Row(");
  buffer.writeln("                  children: [");
  buffer.writeln("                    Icon(statusIcon, color: iconColor, size: 12),");
  buffer.writeln("                    const SizedBox(width: 4),");
  buffer.writeln("                    Text(");
  buffer.writeln("                      statusText,");
  buffer.writeln("                      style: GoogleFonts.poppins(fontSize: 10, fontWeight: FontWeight.w600, color: iconColor),");
  buffer.writeln("                    ),");
  buffer.writeln("                  ],");
  buffer.writeln("                ),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("          ),");
  buffer.writeln("          if (isCompleted || isActive) ...[");
  buffer.writeln("            IconButton(");
  buffer.writeln("              icon: const Icon(Icons.chevron_right_rounded, color: Color(0xFF5B4FCF)),");
  buffer.writeln("              onPressed: () => Get.toNamed('/' + _getStepId(idx)),");
  buffer.writeln("            ),");
  buffer.writeln("          ],");
  buffer.writeln("        ],");
  buffer.writeln("      ),");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();
}
