import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateKanbanLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 800;");
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln();
  buffer.writeln("    // Split steps by status");
  buffer.writeln("    final completedSteps = <Map<String, dynamic>>[];");
  buffer.writeln("    final inProgressSteps = <Map<String, dynamic>>[];");
  buffer.writeln("    final todoSteps = <Map<String, dynamic>>[];");
  buffer.writeln();
  buffer.writeln("    for (int i = 0; i < total; i++) {");
  buffer.writeln("      final title = _getStepTitle(i);");
  buffer.writeln("      final id = _getStepId(i);");
  buffer.writeln("      final item = {'title': title, 'id': id, 'index': i};");
  buffer.writeln("      if (i < activeIdx) {");
  buffer.writeln("        completedSteps.add(item);");
  buffer.writeln("      } else if (i == activeIdx) {");
  buffer.writeln("        inProgressSteps.add(item);");
  buffer.writeln("      } else {");
  buffer.writeln("        todoSteps.add(item);");
  buffer.writeln("      }");
  buffer.writeln("    }");
  buffer.writeln();
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF7F8FC),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              isMobile");
  buffer.writeln("                  ? DefaultTabController(");
  buffer.writeln("                      length: 3,");
  buffer.writeln("                      initialIndex: 1,");
  buffer.writeln("                      child: Column(");
  buffer.writeln("                        children: [");
  buffer.writeln("                          Container(");
  buffer.writeln("                            color: Colors.white,");
  buffer.writeln("                            child: TabBar(");
  buffer.writeln("                              labelColor: const Color(0xFF5B4FCF),");
  buffer.writeln("                              unselectedLabelColor: const Color(0xFF6B7280),");
  buffer.writeln("                              indicatorColor: const Color(0xFF5B4FCF),");
  buffer.writeln("                              labelStyle: GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.bold),");
  buffer.writeln("                              tabs: [");
  buffer.writeln("                                Tab(text: 'Completed (\${completedSteps.length})'),");
  buffer.writeln("                                Tab(text: 'In Progress (\${inProgressSteps.length})'),");
  buffer.writeln("                                Tab(text: 'To Do (\${todoSteps.length})'),");
  buffer.writeln("                              ],");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: TabBarView(");
  buffer.writeln("                              children: [");
  buffer.writeln("                                _buildColumnContainer('Completed', completedSteps, const Color(0xFFE8F9EE), const Color(0xFF22C55E), isMobile, context),");
  buffer.writeln("                                _buildColumnContainer('In Progress', inProgressSteps, const Color(0xFFEEECFD), const Color(0xFF5B4FCF), isMobile, context),");
  buffer.writeln("                                _buildColumnContainer('To Do', todoSteps, const Color(0xFFF3F4F6), const Color(0xFF6B7280), isMobile, context),");
  buffer.writeln("                              ],");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ],");
  buffer.writeln("                      ),");
  buffer.writeln("                    )");
  buffer.writeln("                  : Container(");
  buffer.writeln("                      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),");
  buffer.writeln("                      child: Row(");
  buffer.writeln("                        crossAxisAlignment: CrossAxisAlignment.stretch,");
  buffer.writeln("                        children: [");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: _buildColumnContainer('Completed', completedSteps, const Color(0xFFE8F9EE), const Color(0xFF22C55E), isMobile, context),");
  buffer.writeln("                          ),");
  buffer.writeln("                          const SizedBox(width: 16),");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: _buildColumnContainer('In Progress', inProgressSteps, const Color(0xFFEEECFD), const Color(0xFF5B4FCF), isMobile, context),");
  buffer.writeln("                          ),");
  buffer.writeln("                          const SizedBox(width: 16),");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: _buildColumnContainer('To Do', todoSteps, const Color(0xFFF3F4F6), const Color(0xFF6B7280), isMobile, context),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ],");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}

void generateKanbanHelpers(StringBuffer buffer) {
  buffer.writeln("  Widget _buildColumnContainer(");
  buffer.writeln("    String title,");
  buffer.writeln("    List<Map<String, dynamic>> items,");
  buffer.writeln("    Color bgHeaderColor,");
  buffer.writeln("    Color accentColor,");
  buffer.writeln("    bool isMobile,");
  buffer.writeln("    BuildContext context,");
  buffer.writeln("  ) {");
  buffer.writeln("    return Container(");
  buffer.writeln("      decoration: BoxDecoration(");
  buffer.writeln("        color: Colors.white,");
  buffer.writeln("        borderRadius: BorderRadius.circular(20),");
  buffer.writeln("        border: Border.all(color: const Color(0xFFE4E6F0), width: 1.2),");
  buffer.writeln("      ),");
  buffer.writeln("      child: Column(");
  buffer.writeln("        crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("        children: [");
  buffer.writeln("          // Column Header");
  buffer.writeln("          Container(");
  buffer.writeln("            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),");
  buffer.writeln("            decoration: BoxDecoration(");
  buffer.writeln("              color: bgHeaderColor,");
  buffer.writeln("              borderRadius: const BorderRadius.only(");
  buffer.writeln("                topLeft: Radius.circular(20),");
  buffer.writeln("                topRight: Radius.circular(20),");
  buffer.writeln("              ),");
  buffer.writeln("            ),");
  buffer.writeln("            child: Row(");
  buffer.writeln("              mainAxisAlignment: MainAxisAlignment.spaceBetween,");
  buffer.writeln("              children: [");
  buffer.writeln("                Text(");
  buffer.writeln("                  title,");
  buffer.writeln("                  style: GoogleFonts.poppins(");
  buffer.writeln("                    fontSize: 13,");
  buffer.writeln("                    fontWeight: FontWeight.bold,");
  buffer.writeln("                    color: accentColor,");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("                Container(");
  buffer.writeln("                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),");
  buffer.writeln("                  decoration: BoxDecoration(");
  buffer.writeln("                    color: Colors.white,");
  buffer.writeln("                    borderRadius: BorderRadius.circular(12),");
  buffer.writeln("                  ),");
  buffer.writeln("                  child: Text(");
  buffer.writeln("                    '\${items.length}',");
  buffer.writeln("                    style: GoogleFonts.poppins(");
  buffer.writeln("                      fontSize: 11,");
  buffer.writeln("                      fontWeight: FontWeight.bold,");
  buffer.writeln("                      color: accentColor,");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("          ),");
  buffer.writeln("          ");
  buffer.writeln("          // Cards list");
  buffer.writeln("          Expanded(");
  buffer.writeln("            child: items.isEmpty");
  buffer.writeln("                ? Center(");
  buffer.writeln("                    child: Text(");
  buffer.writeln("                      'No steps in this column',");
  buffer.writeln("                      style: GoogleFonts.poppins(fontSize: 12, color: const Color(0xFFB0B4C8)),");
  buffer.writeln("                    ),");
  buffer.writeln("                  )");
  buffer.writeln("                : ListView.builder(");
  buffer.writeln("                    padding: const EdgeInsets.all(12),");
  buffer.writeln("                    itemCount: items.length,");
  buffer.writeln("                    itemBuilder: (context, idx) {");
  buffer.writeln("                      final item = items[idx];");
  buffer.writeln("                      final stepTitle = item['title'] as String;");
  buffer.writeln("                      final stepId = item['id'] as String;");
  buffer.writeln("                      final sIdx = item['index'] as int;");
  buffer.writeln("                      final isCompleted = idx < sIdx;"); // Index comparison
  buffer.writeln("                      final isActive = sIdx == idx; // In active column context");
  buffer.writeln("                      // active item gets the form builder");
  buffer.writeln("                      final isActualActive = accentColor == const Color(0xFF5B4FCF);");
  buffer.writeln();
  buffer.writeln("                      return Container(");
  buffer.writeln("                        margin: const EdgeInsets.only(bottom: 12),");
  buffer.writeln("                        decoration: BoxDecoration(");
  buffer.writeln("                          color: Colors.white,");
  buffer.writeln("                          borderRadius: BorderRadius.circular(16),");
  buffer.writeln("                          border: Border.all(");
  buffer.writeln("                            color: isActualActive ? const Color(0xFF5B4FCF) : const Color(0xFFE4E6F0),");
  buffer.writeln("                            width: isActualActive ? 1.5 : 1,");
  buffer.writeln("                          ),");
  buffer.writeln("                          boxShadow: [");
  buffer.writeln("                            BoxShadow(");
  buffer.writeln("                              color: Colors.black.withValues(alpha: 0.03),");
  buffer.writeln("                              blurRadius: 10,");
  buffer.writeln("                              offset: const Offset(0, 3),");
  buffer.writeln("                            ),");
  buffer.writeln("                          ],");
  buffer.writeln("                        ),");
  buffer.writeln("                        child: Column(");
  buffer.writeln("                          crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                          children: [");
  buffer.writeln("                            Padding(");
  buffer.writeln("                              padding: const EdgeInsets.all(14.0),");
  buffer.writeln("                              child: Row(");
  buffer.writeln("                                children: [");
  buffer.writeln("                                  Icon(");
  buffer.writeln("                                    isActualActive ? Icons.pending_rounded : (accentColor == const Color(0xFF22C55E) ? Icons.check_circle_rounded : Icons.lock_rounded),");
  buffer.writeln("                                    color: accentColor,");
  buffer.writeln("                                    size: 18,");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  const SizedBox(width: 8),");
  buffer.writeln("                                  Expanded(");
  buffer.writeln("                                    child: Text(");
  buffer.writeln("                                      stepTitle,");
  buffer.writeln("                                      style: GoogleFonts.poppins(");
  buffer.writeln("                                        fontSize: 12,");
  buffer.writeln("                                        fontWeight: FontWeight.bold,");
  buffer.writeln("                                        color: const Color(0xFF1A1A2E),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  if (!isActualActive && accentColor == const Color(0xFF22C55E))");
  buffer.writeln("                                    IconButton(");
  buffer.writeln("                                      icon: const Icon(Icons.edit_rounded, size: 14, color: Color(0xFF5B4FCF)),");
  buffer.writeln("                                      padding: EdgeInsets.zero,");
  buffer.writeln("                                      constraints: const BoxConstraints(),");
  buffer.writeln("                                      onPressed: () => Get.toNamed('/' + stepId),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                ],");
  buffer.writeln("                              ),");
  buffer.writeln("                            ),");
  buffer.writeln("                            if (isActualActive) ...[");
  buffer.writeln("                              const Divider(color: Color(0xFFE4E6F0), height: 1),");
  buffer.writeln("                              Padding(");
  buffer.writeln("                                padding: const EdgeInsets.all(14.0),");
  buffer.writeln("                                child: _buildFormContent(context, isMobile: isMobile),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ],");
  buffer.writeln("                        ),");
  buffer.writeln("                      );");
  buffer.writeln("                    },");
  buffer.writeln("                  ),");
  buffer.writeln("          ),");
  buffer.writeln("        ],");
  buffer.writeln("      ),");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();
}
