import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateMasterDetailLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 760;");
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF0F0FF),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              isMobile");
  buffer.writeln("                  ? SingleChildScrollView(");
  buffer.writeln("                      padding: const EdgeInsets.all(16),");
  buffer.writeln("                      child: _buildFormContent(context, isMobile: true),");
  buffer.writeln("                    )");
  buffer.writeln("                  : Padding(");
  buffer.writeln("                      padding: const EdgeInsets.all(24),");
  buffer.writeln("                      child: Row(");
  buffer.writeln("                        crossAxisAlignment: CrossAxisAlignment.stretch,");
  buffer.writeln("                        children: [");
  buffer.writeln("                          Container(");
  buffer.writeln("                            width: 280,");
  buffer.writeln("                            decoration: BoxDecoration(");
  buffer.writeln("                              color: Colors.white,");
  buffer.writeln("                              borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                              border: Border.all(color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                            ),");
  buffer.writeln("                            child: ListView.builder(");
  buffer.writeln("                              itemCount: total > 0 ? total : 1,");
  buffer.writeln("                              itemBuilder: (context, idx) {");
  buffer.writeln("                                if (total == 0) return const SizedBox.shrink();");
  buffer.writeln("                                final isActive = idx == activeIdx;");
  buffer.writeln("                                final isCompleted = idx < activeIdx;");
  buffer.writeln("                                return Material(");
  buffer.writeln("                                  color: Colors.transparent,");
  buffer.writeln("                                  child: InkWell(");
  buffer.writeln("                                    onTap: idx <= activeIdx ? () => Get.toNamed('/' + _getStepId(idx)) : null,");
  buffer.writeln("                                    child: Container(");
  buffer.writeln("                                      padding: const EdgeInsets.all(16),");
  buffer.writeln("                                      decoration: BoxDecoration(");
  buffer.writeln("                                        color: isActive ? const Color(0xFFF7F5FF) : Colors.transparent,");
  buffer.writeln("                                        border: Border(");
  buffer.writeln("                                          left: BorderSide(");
  buffer.writeln("                                            color: isActive ? const Color(0xFF5B4FCF) : Colors.transparent,");
  buffer.writeln("                                            width: 4,");
  buffer.writeln("                                          ),");
  buffer.writeln("                                          bottom: const BorderSide(color: Color(0xFFF0F0FF)),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      child: Column(");
  buffer.writeln("                                        crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                        children: [");
  buffer.writeln("                                          Row(");
  buffer.writeln("                                            children: [");
  buffer.writeln("                                              Expanded(");
  buffer.writeln("                                                child: Text(");
  buffer.writeln("                                                  _getStepTitle(idx),");
  buffer.writeln("                                                  style: GoogleFonts.poppins(");
  buffer.writeln("                                                    fontWeight: isActive ? FontWeight.bold : FontWeight.w600,");
  buffer.writeln("                                                    fontSize: 13,");
  buffer.writeln("                                                    color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFF1A1A2E),");
  buffer.writeln("                                                  ),");
  buffer.writeln("                                                ),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                              if (isCompleted)");
  buffer.writeln("                                                const Icon(Icons.check_circle_rounded, color: Color(0xFF22C55E), size: 16),");
  buffer.writeln("                                            ],");
  buffer.writeln("                                          ),");
  buffer.writeln("                                          const SizedBox(height: 4),");
  buffer.writeln("                                          Text(");
  buffer.writeln("                                            _getStepDesc(idx),");
  buffer.writeln("                                            style: GoogleFonts.poppins(");
  buffer.writeln("                                              fontSize: 11,");
  buffer.writeln("                                              color: isActive ? const Color(0xFF6B7280) : const Color(0xFFB0B4C8),");
  buffer.writeln("                                            ),");
  buffer.writeln("                                            maxLines: 2,");
  buffer.writeln("                                            overflow: TextOverflow.ellipsis,");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ],");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                );");
  buffer.writeln("                              },");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                          const SizedBox(width: 20),");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: Container(");
  buffer.writeln("                              decoration: BoxDecoration(");
  buffer.writeln("                                color: Colors.white,");
  buffer.writeln("                                borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                                border: Border.all(color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                              ),");
  buffer.writeln("                              padding: const EdgeInsets.all(32),");
  buffer.writeln("                              child: Column(");
  buffer.writeln("                                crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                children: [");
  buffer.writeln("                                  Text(");
  buffer.writeln("                                    '${stepMeta.escapedTitle}',");
  buffer.writeln("                                    style: GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.bold, color: const Color(0xFF1A1A2E)),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  const SizedBox(height: 6),");
  buffer.writeln("                                  Text(");
  buffer.writeln("                                    '${stepMeta.escapedDescription}',");
  buffer.writeln("                                    style: GoogleFonts.poppins(fontSize: 13, color: const Color(0xFF6B7280)),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  const SizedBox(height: 20),");
  buffer.writeln("                                  Expanded(");
  buffer.writeln("                                    child: SingleChildScrollView(");
  buffer.writeln("                                      child: _buildFormContent(context),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ],");
  buffer.writeln("                              ),");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ],");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
