import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateReviewLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 640;");
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    final progressVal = total > 0 ? (activeIdx / total) : 0.0;");
  buffer.writeln();
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF8F9FD),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              SingleChildScrollView(");
  buffer.writeln("                padding: EdgeInsets.symmetric(");
  buffer.writeln("                  horizontal: isMobile ? 16 : 32,");
  buffer.writeln("                  vertical: 24,");
  buffer.writeln("                ),");
  buffer.writeln("                child: Center(");
  buffer.writeln("                  child: ConstrainedBox(");
  buffer.writeln("                    constraints: const BoxConstraints(maxWidth: 900),");
  buffer.writeln("                    child: Column(");
  buffer.writeln("                      crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                      children: [");
  buffer.writeln("                        // Overview Card");
  buffer.writeln("                        Container(");
  buffer.writeln("                          width: double.infinity,");
  buffer.writeln("                          padding: const EdgeInsets.all(24),");
  buffer.writeln("                          decoration: BoxDecoration(");
  buffer.writeln("                            gradient: const LinearGradient(");
  buffer.writeln("                              colors: [Color(0xFF5B4FCF), Color(0xFF7C72E0)],");
  buffer.writeln("                              begin: Alignment.topLeft,");
  buffer.writeln("                              end: Alignment.bottomRight,");
  buffer.writeln("                            ),");
  buffer.writeln("                            borderRadius: BorderRadius.circular(24),");
  buffer.writeln("                            boxShadow: [");
  buffer.writeln("                              BoxShadow(");
  buffer.writeln("                                color: const Color(0xFF5B4FCF).withValues(alpha: 0.2),");
  buffer.writeln("                                blurRadius: 20,");
  buffer.writeln("                                offset: const Offset(0, 8),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                          child: Column(");
  buffer.writeln("                            crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                            children: [");
  buffer.writeln("                              Row(");
  buffer.writeln("                                mainAxisAlignment: MainAxisAlignment.spaceBetween,");
  buffer.writeln("                                children: [");
  buffer.writeln("                                  Column(");
  buffer.writeln("                                    crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                    children: [");
  buffer.writeln("                                      Text(");
  buffer.writeln("                                        'Journey Completion',");
  buffer.writeln("                                        style: GoogleFonts.poppins(");
  buffer.writeln("                                          fontSize: 13,");
  buffer.writeln("                                          color: Colors.white.withValues(alpha: 0.8),");
  buffer.writeln("                                          fontWeight: FontWeight.w500,");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      const SizedBox(height: 4),");
  buffer.writeln("                                      Text(");
  buffer.writeln("                                        '\$activeIdx of \$total steps completed',");
  buffer.writeln("                                        style: GoogleFonts.poppins(");
  buffer.writeln("                                          fontSize: 20,");
  buffer.writeln("                                          color: Colors.white,");
  buffer.writeln("                                          fontWeight: FontWeight.bold,");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ],");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  Container(");
  buffer.writeln("                                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),");
  buffer.writeln("                                    decoration: BoxDecoration(");
  buffer.writeln("                                      color: Colors.white.withValues(alpha: 0.2),");
  buffer.writeln("                                      borderRadius: BorderRadius.circular(16),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                    child: Text(");
  buffer.writeln("                                      '\${(progressVal * 100).toStringAsFixed(0)}%',");
  buffer.writeln("                                      style: GoogleFonts.poppins(");
  buffer.writeln("                                        fontSize: 16,");
  buffer.writeln("                                        color: Colors.white,");
  buffer.writeln("                                        fontWeight: FontWeight.bold,");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ],");
  buffer.writeln("                              ),");
  buffer.writeln("                              const SizedBox(height: 20),");
  buffer.writeln("                              ClipRRect(");
  buffer.writeln("                                borderRadius: BorderRadius.circular(8),");
  buffer.writeln("                                child: LinearProgressIndicator(");
  buffer.writeln("                                  value: progressVal,");
  buffer.writeln("                                  backgroundColor: Colors.white.withValues(alpha: 0.2),");
  buffer.writeln("                                  valueColor: const AlwaysStoppedAnimation<Color>(Colors.white),");
  buffer.writeln("                                  minHeight: 6,");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                        ),");
  buffer.writeln("                        const SizedBox(height: 24),");
  buffer.writeln("                        Text(");
  buffer.writeln("                          'Journey Review Summary',");
  buffer.writeln("                          style: GoogleFonts.poppins(");
  buffer.writeln("                            fontSize: 16,");
  buffer.writeln("                            fontWeight: FontWeight.bold,");
  buffer.writeln("                            color: const Color(0xFF1A1A2E),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ),");
  buffer.writeln("                        const SizedBox(height: 12),");
  buffer.writeln("                        ");
  buffer.writeln("                        // List of steps and values");
  buffer.writeln("                        ...List.generate(total, (idx) {");
  buffer.writeln("                          final isCompleted = idx < activeIdx;");
  buffer.writeln("                          final isActive = idx == activeIdx;");
  buffer.writeln("                          final isUpcoming = idx > activeIdx;");
  buffer.writeln("                          final stepTitle = _getStepTitle(idx);");
  buffer.writeln("                          final stepId = _getStepId(idx);");
  buffer.writeln();
  buffer.writeln("                          Color statusColor;");
  buffer.writeln("                          String statusText;");
  buffer.writeln("                          IconData statusIcon;");
  buffer.writeln("                          if (isCompleted) {");
  buffer.writeln("                            statusColor = const Color(0xFF22C55E);");
  buffer.writeln("                            statusText = 'Completed';");
  buffer.writeln("                            statusIcon = Icons.check_circle_rounded;");
  buffer.writeln("                          } else if (isActive) {");
  buffer.writeln("                            statusColor = const Color(0xFF5B4FCF);");
  buffer.writeln("                            statusText = 'Active (In Progress)';");
  buffer.writeln("                            statusIcon = Icons.pending_rounded;");
  buffer.writeln("                          } else {");
  buffer.writeln("                            statusColor = const Color(0xFF6B7280);");
  buffer.writeln("                            statusText = 'Pending';");
  buffer.writeln("                            statusIcon = Icons.lock_rounded;");
  buffer.writeln("                          }");
  buffer.writeln();
  buffer.writeln("                          return Container(");
  buffer.writeln("                            margin: const EdgeInsets.only(bottom: 16),");
  buffer.writeln("                            decoration: BoxDecoration(");
  buffer.writeln("                              color: Colors.white,");
  buffer.writeln("                              borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                              border: Border.all(");
  buffer.writeln("                                color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFFE4E6F0).withValues(alpha: 0.8),");
  buffer.writeln("                                width: isActive ? 1.5 : 1,");
  buffer.writeln("                              ),");
  buffer.writeln("                              boxShadow: isActive");
  buffer.writeln("                                  ? [");
  buffer.writeln("                                      BoxShadow(");
  buffer.writeln("                                        color: const Color(0xFF5B4FCF).withValues(alpha: 0.05),");
  buffer.writeln("                                        blurRadius: 20,");
  buffer.writeln("                                        offset: const Offset(0, 6),");
  buffer.writeln("                                      )");
  buffer.writeln("                                    ]");
  buffer.writeln("                                  : null,");
  buffer.writeln("                            ),");
  buffer.writeln("                            child: ExpansionTile(");
  buffer.writeln("                              key: PageStorageKey('review_step_\$idx'),");
  buffer.writeln("                              initiallyExpanded: isActive || isCompleted,");
  buffer.writeln("                              leading: Icon(statusIcon, color: statusColor, size: 24),");
  buffer.writeln("                              title: Text(");
  buffer.writeln("                                stepTitle,");
  buffer.writeln("                                style: GoogleFonts.poppins(");
  buffer.writeln("                                  fontSize: 14,");
  buffer.writeln("                                  fontWeight: FontWeight.bold,");
  buffer.writeln("                                  color: const Color(0xFF1A1A2E),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                              subtitle: Text(");
  buffer.writeln("                                statusText,");
  buffer.writeln("                                style: GoogleFonts.poppins(");
  buffer.writeln("                                  fontSize: 11,");
  buffer.writeln("                                  color: statusColor,");
  buffer.writeln("                                  fontWeight: FontWeight.w500,");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                              trailing: (isCompleted || isActive)");
  buffer.writeln("                                  ? TextButton.icon(");
  buffer.writeln("                                      icon: const Icon(Icons.edit_rounded, size: 14),");
  buffer.writeln("                                      label: Text(");
  buffer.writeln("                                        'Edit',");
  buffer.writeln("                                        style: GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.bold),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      onPressed: () {");
  buffer.writeln("                                        Get.toNamed('/' + stepId);");
  buffer.writeln("                                      },");
  buffer.writeln("                                    )");
  buffer.writeln("                                  : const Icon(Icons.chevron_right_rounded),");
  buffer.writeln("                              childrenPadding: const EdgeInsets.all(20),");
  buffer.writeln("                              expandedCrossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                              children: [");
  buffer.writeln("                                if (isUpcoming)");
  buffer.writeln("                                  Padding(");
  buffer.writeln("                                    padding: const EdgeInsets.symmetric(vertical: 8.0),");
  buffer.writeln("                                    child: Text(");
  buffer.writeln("                                      'Complete previous steps to unlock this section.',");
  buffer.writeln("                                      style: GoogleFonts.poppins(fontSize: 12, color: const Color(0xFF6B7280), fontStyle: FontStyle.italic),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  )");
  buffer.writeln("                                else if (isActive)");
  buffer.writeln("                                  Column(");
  buffer.writeln("                                    crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                    children: [");
  buffer.writeln("                                      Container(");
  buffer.writeln("                                        padding: const EdgeInsets.all(12),");
  buffer.writeln("                                        margin: const EdgeInsets.only(bottom: 18),");
  buffer.writeln("                                        decoration: BoxDecoration(");
  buffer.writeln("                                          color: const Color(0xFFEEECFD),");
  buffer.writeln("                                          borderRadius: BorderRadius.circular(12),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                        child: Row(");
  buffer.writeln("                                          children: [");
  buffer.writeln("                                            const Icon(Icons.info_outline_rounded, color: Color(0xFF5B4FCF), size: 16),");
  buffer.writeln("                                            const SizedBox(width: 8),");
  buffer.writeln("                                            Expanded(");
  buffer.writeln("                                              child: Text(");
  buffer.writeln("                                                'You are currently filling out this step. Complete the inputs below:',");
  buffer.writeln("                                                style: GoogleFonts.poppins(");
  buffer.writeln("                                                  fontSize: 11,");
  buffer.writeln("                                                  color: const Color(0xFF5B4FCF),");
  buffer.writeln("                                                  fontWeight: FontWeight.w600,");
  buffer.writeln("                                                ),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                            ),");
  buffer.writeln("                                          ],");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      _buildFormContent(context, isMobile: isMobile),");
  buffer.writeln("                                    ],");
  buffer.writeln("                                  )");
  buffer.writeln("                                else");
  buffer.writeln("                                  Padding(");
  buffer.writeln("                                    padding: const EdgeInsets.symmetric(vertical: 8.0),");
  buffer.writeln("                                    child: Text(");
  buffer.writeln("                                      'Step completed. Tap Edit to view or change answers.',");
  buffer.writeln("                                      style: GoogleFonts.poppins(fontSize: 12, color: const Color(0xFF6B7280), fontStyle: FontStyle.italic),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                              ],");
  buffer.writeln("                            ),");
  buffer.writeln("                          );");
  buffer.writeln("                        }),");
  buffer.writeln("                      ],");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("              ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
