import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateSplitLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
) {
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 640;");
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF0F0FF),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              isMobile");
  buffer.writeln("                  ? SingleChildScrollView(");
  buffer.writeln("                      padding: const EdgeInsets.all(16),");
  buffer.writeln("                      child: _buildFormContent(context, isMobile: true),");
  buffer.writeln("                    )");
  buffer.writeln("                  : Center(");
  buffer.writeln("                      child: ConstrainedBox(");
  buffer.writeln("                        constraints: const BoxConstraints(maxWidth: 1060),");
  buffer.writeln("                        child: Container(");
  buffer.writeln("                          margin: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),");
  buffer.writeln("                          decoration: BoxDecoration(");
  buffer.writeln("                            color: Colors.white,");
  buffer.writeln("                            borderRadius: BorderRadius.circular(24),");
  buffer.writeln("                            boxShadow: const [");
  buffer.writeln("                              BoxShadow(");
  buffer.writeln("                                color: Color(0x125B4FCF),");
  buffer.writeln("                                blurRadius: 40,");
  buffer.writeln("                                offset: Offset(0, 8),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                          child: Row(");
  buffer.writeln("                            crossAxisAlignment: CrossAxisAlignment.stretch,");
  buffer.writeln("                            children: [");
  buffer.writeln("                              // Left info panel");
  buffer.writeln("                              Container(");
  buffer.writeln("                                width: 270,");
  buffer.writeln("                                decoration: const BoxDecoration(");
  buffer.writeln("                                  color: Color(0xFFF7F5FF),");
  buffer.writeln("                                  borderRadius: BorderRadius.only(");
  buffer.writeln("                                    topLeft: Radius.circular(24),");
  buffer.writeln("                                    bottomLeft: Radius.circular(24),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ),");
  buffer.writeln("                                padding: const EdgeInsets.all(26),");
  buffer.writeln("                                child: Column(");
  buffer.writeln("                                  crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                  children: [");
  buffer.writeln("                                    Container(");
  buffer.writeln("                                      width: 48,");
  buffer.writeln("                                      height: 48,");
  buffer.writeln("                                      decoration: BoxDecoration(");
  buffer.writeln("                                        color: const Color(0xFF5B4FCF),");
  buffer.writeln("                                        shape: BoxShape.circle,");
  buffer.writeln("                                        boxShadow: [");
  buffer.writeln("                                          BoxShadow(");
  buffer.writeln("                                            color: const Color(0xFF5B4FCF).withValues(alpha: 0.28),");
  buffer.writeln("                                            blurRadius: 14,");
  buffer.writeln("                                            offset: const Offset(0, 4),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ],");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      child: Icon(_stepIconForTitle('${stepMeta.escapedTitle}'), color: Colors.white, size: 22),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                    const SizedBox(height: 18),");
  buffer.writeln("                                    Text(");
  buffer.writeln("                                      '${stepMeta.escapedTitle}',");
  buffer.writeln("                                      style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold, color: const Color(0xFF1A1A2E)),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                    const SizedBox(height: 6),");
  buffer.writeln("                                    Text(");
  buffer.writeln("                                      '${stepMeta.escapedDescription}',");
  buffer.writeln("                                      style: theme.textTheme.bodySmall?.copyWith(color: const Color(0xFF6B7280), height: 1.5),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                    const Spacer(),");
  buffer.writeln("                                    Center(child: _buildIllustration('${stepMeta.escapedTitle}')),");
  buffer.writeln("                                    const Spacer(),");
  buffer.writeln("                                    _buildStepMiniList(),");
  buffer.writeln("                                    const Spacer(),");
  buffer.writeln("                                    Container(");
  buffer.writeln("                                      padding: const EdgeInsets.all(12),");
  buffer.writeln("                                      decoration: BoxDecoration(");
  buffer.writeln("                                        color: Colors.white,");
  buffer.writeln("                                        borderRadius: BorderRadius.circular(12),");
  buffer.writeln("                                        border: Border.all(color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      child: Row(");
  buffer.writeln("                                        children: [");
  buffer.writeln("                                          const Icon(Icons.lock_outline_rounded, color: Color(0xFF5B4FCF), size: 16),");
  buffer.writeln("                                          const SizedBox(width: 8),");
  buffer.writeln("                                          Expanded(");
  buffer.writeln("                                            child: Text(");
  buffer.writeln("                                              'End-to-end encrypted details',");
  buffer.writeln("                                              style: theme.textTheme.bodySmall?.copyWith(fontSize: 10, fontWeight: FontWeight.w600, color: const Color(0xFF1A1A2E)),");
  buffer.writeln("                                            ),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ],");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ],");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                              Container(width: 1, color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                              // Right form panel");
  buffer.writeln("                              Expanded(");
  buffer.writeln("                                child: ClipRRect(");
  buffer.writeln("                                  borderRadius: const BorderRadius.only(");
  buffer.writeln("                                    topRight: Radius.circular(24),");
  buffer.writeln("                                    bottomRight: Radius.circular(24),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  child: SingleChildScrollView(");
  buffer.writeln("                                    padding: const EdgeInsets.all(32),");
  buffer.writeln("                                    child: _buildFormContent(context, isMobile: false),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                        ),");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}

void generateSplitHelpers(StringBuffer buffer, int activeIdxClamp, int totalSteps) {
  buffer.writeln("  Widget _buildStepMiniList() {");
  buffer.writeln("    final total = $totalSteps;");
  buffer.writeln("    if (total <= 1) return const SizedBox.shrink();");
  buffer.writeln("    return Row(");
  buffer.writeln("      mainAxisAlignment: MainAxisAlignment.center,");
  buffer.writeln("      children: List.generate(total > 7 ? 7 : total, (i) {");
  buffer.writeln("        final idx = i;");
  buffer.writeln("        final isActive = idx == $activeIdxClamp;");
  buffer.writeln("        final isDone = idx < $activeIdxClamp;");
  buffer.writeln("        return Container(");
  buffer.writeln("          width: isActive ? 22 : 8,");
  buffer.writeln("          height: 8,");
  buffer.writeln("          margin: const EdgeInsets.symmetric(horizontal: 3),");
  buffer.writeln("          decoration: BoxDecoration(");
  buffer.writeln("            color: isActive");
  buffer.writeln("                ? const Color(0xFF5B4FCF)");
  buffer.writeln("                : isDone");
  buffer.writeln("                    ? const Color(0xFF5B4FCF).withValues(alpha: 0.3)");
  buffer.writeln("                    : const Color(0xFFE4E6F0),");
  buffer.writeln("            borderRadius: BorderRadius.circular(4),");
  buffer.writeln("          ),");
  buffer.writeln("        );");
  buffer.writeln("      }),");
  buffer.writeln("    );");
  buffer.writeln("  }");
  buffer.writeln();
}
