import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateStepperLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final screenW = MediaQuery.of(context).size.width;");
  buffer.writeln("    final isMobile = screenW < 720;");
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln();
  buffer.writeln("    return Theme(");
  buffer.writeln("      data: Theme.of(context).copyWith(");
  buffer.writeln("        colorScheme: const ColorScheme.light(");
  buffer.writeln("          primary: Color(0xFF5B4FCF),");
  buffer.writeln("          secondary: Color(0xFF5B4FCF),");
  buffer.writeln("          surface: Colors.white,");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("      child: Scaffold(");
  buffer.writeln("        backgroundColor: const Color(0xFFF7F8FC),");
  buffer.writeln("        appBar: AppBar(");
  buffer.writeln("          title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("          backgroundColor: Colors.white,");
  buffer.writeln("          foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("          elevation: 0,");
  buffer.writeln("          centerTitle: true,");
  buffer.writeln("        ),");
  buffer.writeln("        body: GestureDetector(");
  buffer.writeln("          onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("          child: SafeArea(");
  buffer.writeln("            child: Stack(");
  buffer.writeln("              children: [");
  buffer.writeln("                SingleChildScrollView(");
  buffer.writeln("                  padding: EdgeInsets.symmetric(");
  buffer.writeln("                    horizontal: isMobile ? 12 : 24,");
  buffer.writeln("                    vertical: 20,");
  buffer.writeln("                  ),");
  buffer.writeln("                  child: Center(");
  buffer.writeln("                    child: ConstrainedBox(");
  buffer.writeln("                      constraints: const BoxConstraints(maxWidth: 900),");
  buffer.writeln("                      child: Container(");
  buffer.writeln("                        decoration: BoxDecoration(");
  buffer.writeln("                          color: Colors.white,");
  buffer.writeln("                          borderRadius: BorderRadius.circular(24),");
  buffer.writeln("                          border: Border.all(color: const Color(0xFFE4E6F0), width: 1.2),");
  buffer.writeln("                          boxShadow: [");
  buffer.writeln("                            BoxShadow(");
  buffer.writeln("                              color: const Color(0xFF5B4FCF).withValues(alpha: 0.04),");
  buffer.writeln("                              blurRadius: 20,");
  buffer.writeln("                              offset: const Offset(0, 4),");
  buffer.writeln("                            ),");
  buffer.writeln("                          ],");
  buffer.writeln("                        ),");
  buffer.writeln("                        child: Stepper(");
  buffer.writeln("                          type: isMobile ? StepperType.vertical : StepperType.horizontal,");
  buffer.writeln("                          currentStep: activeIdx,");
  buffer.writeln("                          onStepTapped: (idx) {");
  buffer.writeln("                            if (idx <= activeIdx) {");
  buffer.writeln("                              Get.toNamed('/' + _getStepId(idx));");
  buffer.writeln("                            }");
  buffer.writeln("                          },");
  buffer.writeln("                          controlsBuilder: (context, details) {");
  buffer.writeln("                            // Suppress stepper's default continue/cancel buttons");
  buffer.writeln("                            return const SizedBox.shrink();");
  buffer.writeln("                          },");
  buffer.writeln("                          steps: List.generate(total, (idx) {");
  buffer.writeln("                            final stepTitle = _getStepTitle(idx);");
  buffer.writeln("                            final isCompleted = idx < activeIdx;");
  buffer.writeln("                            final isActive = idx == activeIdx;");
  buffer.writeln("                            ");
  buffer.writeln("                            StepState state;");
  buffer.writeln("                            if (isCompleted) {");
  buffer.writeln("                              state = StepState.complete;");
  buffer.writeln("                            } else if (isActive) {");
  buffer.writeln("                              state = StepState.editing;");
  buffer.writeln("                            } else {");
  buffer.writeln("                              state = StepState.disabled;");
  buffer.writeln("                            }");
  buffer.writeln();
  buffer.writeln("                            return Step(");
  buffer.writeln("                              title: Text(");
  buffer.writeln("                                stepTitle,");
  buffer.writeln("                                style: GoogleFonts.poppins(");
  buffer.writeln("                                  fontSize: 12,");
  buffer.writeln("                                  fontWeight: isActive ? FontWeight.bold : FontWeight.w500,");
  buffer.writeln("                                  color: isActive ? const Color(0xFF1A1A2E) : const Color(0xFF6B7280),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                              subtitle: isMobile ? null : Text(");
  buffer.writeln("                                isActive ? 'Active' : (isCompleted ? 'Done' : 'Locked'),");
  buffer.writeln("                                style: GoogleFonts.poppins(fontSize: 10),");
  buffer.writeln("                              ),");
  buffer.writeln("                              state: state,");
  buffer.writeln("                              isActive: isActive || isCompleted,");
  buffer.writeln("                              content: isActive");
  buffer.writeln("                                  ? Padding(");
  buffer.writeln("                                      padding: const EdgeInsets.symmetric(vertical: 12.0),");
  buffer.writeln("                                      child: _buildFormContent(context, isMobile: isMobile),");
  buffer.writeln("                                    )");
  buffer.writeln("                                  : Container(),");
  buffer.writeln("                            );");
  buffer.writeln("                          }),");
  buffer.writeln("                        ),");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                ),");
  buffer.writeln("                _buildLoadingOverlay(),");
  buffer.writeln("              ],");
  buffer.writeln("            ),");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
