import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateTabbedLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 800;");
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF0F0FF),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              isMobile");
  buffer.writeln("                  ? SingleChildScrollView(");
  buffer.writeln("                      padding: const EdgeInsets.all(16),");
  buffer.writeln("                      child: _buildFormContent(context, isMobile: true),");
  buffer.writeln("                    )");
  buffer.writeln("                  : Padding(");
  buffer.writeln("                      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),");
  buffer.writeln("                      child: Row(");
  buffer.writeln("                        crossAxisAlignment: CrossAxisAlignment.stretch,");
  buffer.writeln("                        children: [");
  buffer.writeln("                          Container(");
  buffer.writeln("                            width: 220,");
  buffer.writeln("                            decoration: BoxDecoration(");
  buffer.writeln("                              color: const Color(0xFFF7F5FF),");
  buffer.writeln("                              borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                              border: Border.all(color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                            ),");
  buffer.writeln("                            padding: const EdgeInsets.all(16),");
  buffer.writeln("                            child: Column(");
  buffer.writeln("                              crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                              children: [");
  buffer.writeln("                                Text(");
  buffer.writeln("                                  'JOURNEY STEPS',");
  buffer.writeln("                                  style: GoogleFonts.poppins(");
  buffer.writeln("                                    fontWeight: FontWeight.bold,");
  buffer.writeln("                                    color: const Color(0xFF6B7280),");
  buffer.writeln("                                    fontSize: 10,");
  buffer.writeln("                                    letterSpacing: 1.2,");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ),");
  buffer.writeln("                                const SizedBox(height: 12),");
  buffer.writeln("                                Expanded(");
  buffer.writeln("                                  child: ListView.builder(");
  buffer.writeln("                                    itemCount: total > 0 ? total : 1,");
  buffer.writeln("                                    itemBuilder: (context, idx) {");
  buffer.writeln("                                      if (total == 0) return const SizedBox.shrink();");
  buffer.writeln("                                      final isActive = idx == activeIdx;");
  buffer.writeln("                                      final isCompleted = idx < activeIdx;");
  buffer.writeln("                                      return InkWell(");
  buffer.writeln("                                        onTap: (isCompleted || isActive) ? () => Get.toNamed('/' + _getStepId(idx)) : null,");
  buffer.writeln("                                        child: Container(");
  buffer.writeln("                                          margin: const EdgeInsets.only(bottom: 8),");
  buffer.writeln("                                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),");
  buffer.writeln("                                          decoration: BoxDecoration(");
  buffer.writeln("                                            color: isActive");
  buffer.writeln("                                                ? const Color(0xFF5B4FCF)");
  buffer.writeln("                                                : Colors.transparent,");
  buffer.writeln("                                            borderRadius: BorderRadius.circular(10),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                          child: Row(");
  buffer.writeln("                                            children: [");
  buffer.writeln("                                              Icon(");
  buffer.writeln("                                                isCompleted ? Icons.check_circle_rounded : Icons.circle,");
  buffer.writeln("                                                size: isCompleted ? 14 : 8,");
  buffer.writeln("                                                color: isActive");
  buffer.writeln("                                                    ? Colors.white");
  buffer.writeln("                                                    : isCompleted");
  buffer.writeln("                                                        ? const Color(0xFF22C55E)");
  buffer.writeln("                                                        : const Color(0xFFB0B4C8),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                              const SizedBox(width: 8),");
  buffer.writeln("                                              Expanded(");
  buffer.writeln("                                                child: Text(");
  buffer.writeln("                                                  _getStepTitle(idx),");
  buffer.writeln("                                                  style: GoogleFonts.poppins(");
  buffer.writeln("                                                    fontWeight: isActive ? FontWeight.bold : FontWeight.w500,");
  buffer.writeln("                                                    color: isActive ? Colors.white : const Color(0xFF1A1A2E),");
  buffer.writeln("                                                    fontSize: 12,");
  buffer.writeln("                                                  ),");
  buffer.writeln("                                                  overflow: TextOverflow.ellipsis,");
  buffer.writeln("                                                ),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                            ],");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      );");
  buffer.writeln("                                    },");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ],");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                          const SizedBox(width: 16),");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: Container(");
  buffer.writeln("                              decoration: BoxDecoration(");
  buffer.writeln("                                color: Colors.white,");
  buffer.writeln("                                borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                                border: Border.all(color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                                boxShadow: const [");
  buffer.writeln("                                  BoxShadow(");
  buffer.writeln("                                    color: Color(0x085B4FCF),");
  buffer.writeln("                                    blurRadius: 20,");
  buffer.writeln("                                    offset: Offset(0, 4),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ],");
  buffer.writeln("                              ),");
  buffer.writeln("                              child: ClipRRect(");
  buffer.writeln("                                borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                                child: SingleChildScrollView(");
  buffer.writeln("                                  padding: const EdgeInsets.all(28),");
  buffer.writeln("                                  child: _buildFormContent(context),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                          const SizedBox(width: 16),");
  buffer.writeln("                          Container(");
  buffer.writeln("                            width: 240,");
  buffer.writeln("                            decoration: BoxDecoration(");
  buffer.writeln("                              color: Colors.white,");
  buffer.writeln("                              borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                              border: Border.all(color: const Color(0xFFE4E6F0)),");
  buffer.writeln("                            ),");
  buffer.writeln("                            padding: const EdgeInsets.all(20),");
  buffer.writeln("                            child: _buildLiveSummaryCard(context),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ],");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
