import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateTimelineLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF0F0FF),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              ListView.builder(");
  buffer.writeln("                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 24),");
  buffer.writeln("                itemCount: total > 0 ? total : 1,");
  buffer.writeln("                itemBuilder: (context, index) {");
  buffer.writeln("                  if (total == 0) {");
  buffer.writeln("                    return Center(");
  buffer.writeln("                      child: ConstrainedBox(");
  buffer.writeln("                        constraints: const BoxConstraints(maxWidth: 800),");
  buffer.writeln("                        child: Container(");
  buffer.writeln("                          padding: const EdgeInsets.all(24),");
  buffer.writeln("                          decoration: BoxDecoration(");
  buffer.writeln("                            color: Colors.white,");
  buffer.writeln("                            borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                            border: Border.all(color: const Color(0xFF5B4FCF), width: 1.5),");
  buffer.writeln("                          ),");
  buffer.writeln("                          child: _buildFormContent(context),");
  buffer.writeln("                        ),");
  buffer.writeln("                      ),");
  buffer.writeln("                    );");
  buffer.writeln("                  }");
  buffer.writeln("                  final isCompleted = index < activeIdx;");
  buffer.writeln("                  final isActive = index == activeIdx;");
  buffer.writeln("                  final stepTitle = _getStepTitle(index);");
  buffer.writeln("                  final stepId = _getStepId(index);");
  buffer.writeln("                  return Center(");
  buffer.writeln("                    child: ConstrainedBox(");
  buffer.writeln("                      constraints: const BoxConstraints(maxWidth: 800),");
  buffer.writeln("                      child: Row(");
  buffer.writeln("                        crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                        children: [");
  buffer.writeln("                          Column(");
  buffer.writeln("                            children: [");
  buffer.writeln("                              AnimatedContainer(");
  buffer.writeln("                                duration: const Duration(milliseconds: 250),");
  buffer.writeln("                                width: 32,");
  buffer.writeln("                                height: 32,");
  buffer.writeln("                                decoration: BoxDecoration(");
  buffer.writeln("                                  color: isActive");
  buffer.writeln("                                      ? const Color(0xFF5B4FCF)");
  buffer.writeln("                                      : isCompleted");
  buffer.writeln("                                          ? const Color(0xFF22C55E)");
  buffer.writeln("                                          : Colors.white,");
  buffer.writeln("                                  shape: BoxShape.circle,");
  buffer.writeln("                                  border: Border.all(");
  buffer.writeln("                                    color: isActive");
  buffer.writeln("                                        ? const Color(0xFF5B4FCF)");
  buffer.writeln("                                        : isCompleted");
  buffer.writeln("                                            ? const Color(0xFF22C55E)");
  buffer.writeln("                                            : const Color(0xFFE4E6F0),");
  buffer.writeln("                                    width: 2,");
  buffer.writeln("                                  ),");
  buffer.writeln("                                ),");
  buffer.writeln("                                child: Center(");
  buffer.writeln("                                  child: isCompleted");
  buffer.writeln("                                      ? const Icon(Icons.check_rounded, size: 16, color: Colors.white)");
  buffer.writeln("                                      : Text(");
  buffer.writeln("                                          '\${index + 1}',");
  buffer.writeln("                                          style: GoogleFonts.poppins(");
  buffer.writeln("                                            fontSize: 12,");
  buffer.writeln("                                            fontWeight: FontWeight.bold,");
  buffer.writeln("                                            color: isActive ? Colors.white : const Color(0xFFB0B4C8),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ),");
  buffer.writeln("                              if (index < total - 1)");
  buffer.writeln("                                Container(");
  buffer.writeln("                                  width: 2,");
  buffer.writeln("                                  height: isActive ? 180 : 80,");
  buffer.writeln("                                  color: isCompleted ? const Color(0xFF22C55E) : const Color(0xFFE4E6F0),");
  buffer.writeln("                                ),");
  buffer.writeln("                            ],");
  buffer.writeln("                          ),");
  buffer.writeln("                          const SizedBox(width: 16),");
  buffer.writeln("                          Expanded(");
  buffer.writeln("                            child: Padding(");
  buffer.writeln("                              padding: const EdgeInsets.only(bottom: 24),");
  buffer.writeln("                              child: isActive");
  buffer.writeln("                                  ? Container(");
  buffer.writeln("                                      decoration: BoxDecoration(");
  buffer.writeln("                                        color: Colors.white,");
  buffer.writeln("                                        borderRadius: BorderRadius.circular(20),");
  buffer.writeln("                                        border: Border.all(color: const Color(0xFF5B4FCF), width: 1.5),");
  buffer.writeln("                                        boxShadow: const [");
  buffer.writeln("                                          BoxShadow(");
  buffer.writeln("                                            color: Color(0x085B4FCF),");
  buffer.writeln("                                            blurRadius: 30,");
  buffer.writeln("                                            offset: Offset(0, 6),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ],");
  buffer.writeln("                                      ),");
  buffer.writeln("                                      padding: const EdgeInsets.all(24),");
  buffer.writeln("                                      child: _buildFormContent(context),");
  buffer.writeln("                                    )");
  buffer.writeln("                                  : isCompleted");
  buffer.writeln("                                      ? GestureDetector(");
  buffer.writeln("                                          onTap: () => Get.toNamed('/\$stepId'),");
  buffer.writeln("                                          child: Container(");
  buffer.writeln("                                            decoration: BoxDecoration(");
  buffer.writeln("                                              color: const Color(0xFFE8F9EE).withValues(alpha: 0.4),");
  buffer.writeln("                                              borderRadius: BorderRadius.circular(16),");
  buffer.writeln("                                              border: Border.all(color: const Color(0xFF22C55E).withValues(alpha: 0.15)),");
  buffer.writeln("                                            ),");
  buffer.writeln("                                            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),");
  buffer.writeln("                                            child: Row(");
  buffer.writeln("                                              children: [");
  buffer.writeln("                                                Expanded(");
  buffer.writeln("                                                  child: Column(");
  buffer.writeln("                                                    crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                                    children: [");
  buffer.writeln("                                                      Row(");
  buffer.writeln("                                                        children: [");
  buffer.writeln("                                                          Text(");
  buffer.writeln("                                                            stepTitle,");
  buffer.writeln("                                                            style: GoogleFonts.poppins(");
  buffer.writeln("                                                              fontSize: 14,");
  buffer.writeln("                                                              fontWeight: FontWeight.w600,");
  buffer.writeln("                                                              color: const Color(0xFF1A1A2E),");
  buffer.writeln("                                                            ),");
  buffer.writeln("                                                          ),");
  buffer.writeln("                                                          const SizedBox(width: 8),");
  buffer.writeln("                                                          Container(");
  buffer.writeln("                                                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),");
  buffer.writeln("                                                            decoration: BoxDecoration(");
  buffer.writeln("                                                              color: const Color(0xFFE8F9EE),");
  buffer.writeln("                                                              borderRadius: BorderRadius.circular(12),");
  buffer.writeln("                                                            ),");
  buffer.writeln("                                                            child: Text(");
  buffer.writeln("                                                              'Completed',");
  buffer.writeln("                                                              style: GoogleFonts.poppins(");
  buffer.writeln("                                                                fontSize: 10,");
  buffer.writeln("                                                                fontWeight: FontWeight.w600,");
  buffer.writeln("                                                                color: const Color(0xFF22C55E),");
  buffer.writeln("                                                              ),");
  buffer.writeln("                                                            ),");
  buffer.writeln("                                                          ),");
  buffer.writeln("                                                        ],");
  buffer.writeln("                                                      ),");
  buffer.writeln("                                                      const SizedBox(height: 4),");
  buffer.writeln("                                                      Text(");
  buffer.writeln("                                                        'Tap Edit to modify answers',");
  buffer.writeln("                                                        style: GoogleFonts.poppins(fontSize: 11, color: const Color(0xFF6B7280)),");
  buffer.writeln("                                                      ),");
  buffer.writeln("                                                    ],");
  buffer.writeln("                                                  ),");
  buffer.writeln("                                                ),");
  buffer.writeln("                                                TextButton.icon(");
  buffer.writeln("                                                  onPressed: () => Get.toNamed('/\$stepId'),");
  buffer.writeln("                                                  icon: const Icon(Icons.edit_outlined, size: 14, color: Color(0xFF5B4FCF)),");
  buffer.writeln("                                                  label: Text(");
  buffer.writeln("                                                    'Edit',");
  buffer.writeln("                                                    style: GoogleFonts.poppins(");
  buffer.writeln("                                                      fontSize: 12,");
  buffer.writeln("                                                      fontWeight: FontWeight.w600,");
  buffer.writeln("                                                      color: const Color(0xFF5B4FCF),");
  buffer.writeln("                                                    ),");
  buffer.writeln("                                                  ),");
  buffer.writeln("                                                ),");
  buffer.writeln("                                              ],");
  buffer.writeln("                                            ),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        )");
  buffer.writeln("                                      : Container(");
  buffer.writeln("                                          decoration: BoxDecoration(");
  buffer.writeln("                                            color: const Color(0xFFFAFAFF),");
  buffer.writeln("                                            borderRadius: BorderRadius.circular(16),");
  buffer.writeln("                                            border: Border.all(color: const Color(0xFFE4E6F0).withValues(alpha: 0.5)),");
  buffer.writeln("                                          ),");
  buffer.writeln("                                          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),");
  buffer.writeln("                                          child: Row(");
  buffer.writeln("                                            children: [");
  buffer.writeln("                                              const Icon(Icons.lock_outline_rounded, size: 18, color: Color(0xFFB0B4C8)),");
  buffer.writeln("                                              const SizedBox(width: 12),");
  buffer.writeln("                                              Expanded(");
  buffer.writeln("                                                child: Column(");
  buffer.writeln("                                                  crossAxisAlignment: CrossAxisAlignment.start,");
  buffer.writeln("                                                  children: [");
  buffer.writeln("                                                    Text(");
  buffer.writeln("                                                      stepTitle,");
  buffer.writeln("                                                      style: GoogleFonts.poppins(");
  buffer.writeln("                                                        fontSize: 14,");
  buffer.writeln("                                                        fontWeight: FontWeight.w500,");
  buffer.writeln("                                                        color: const Color(0xFFB0B4C8),");
  buffer.writeln("                                                      ),");
  buffer.writeln("                                                    ),");
  buffer.writeln("                                                    Text(");
  buffer.writeln("                                                      'Locked until previous steps are completed',");
  buffer.writeln("                                                      style: GoogleFonts.poppins(");
  buffer.writeln("                                                        fontSize: 11,");
  buffer.writeln("                                                        color: const Color(0xFFB0B4C8),");
  buffer.writeln("                                                      ),");
  buffer.writeln("                                                    ),");
  buffer.writeln("                                                  ],");
  buffer.writeln("                                                ),");
  buffer.writeln("                                              ),");
  buffer.writeln("                                            ],");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ),");
  buffer.writeln("                            ),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ],");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("                  );");
  buffer.writeln("                },");
  buffer.writeln("              ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
