import 'package:revojourneytryone/codegenerator/filegegnerator/journey_step_codegen.dart';

void generateWizardLayout(
  StringBuffer buffer,
  JourneyStepCodegen stepMeta,
  String className,
  List<dynamic> stepsList,
  int activeIdxClamp,
) {
  final total = stepsList.length;
  buffer.writeln("    final isMobile = MediaQuery.of(context).size.width < 640;");
  buffer.writeln("    final total = $total;");
  buffer.writeln("    final activeIdx = $activeIdxClamp;");
  buffer.writeln("    return Scaffold(");
  buffer.writeln("      backgroundColor: const Color(0xFFF8F9FD),");
  buffer.writeln("      appBar: AppBar(");
  buffer.writeln("        title: const Text('${stepMeta.escapedTitle}'),");
  buffer.writeln("        backgroundColor: Colors.white,");
  buffer.writeln("        foregroundColor: const Color(0xFF1A1A2E),");
  buffer.writeln("        elevation: 0,");
  buffer.writeln("        centerTitle: true,");
  buffer.writeln("      ),");
  buffer.writeln("      body: GestureDetector(");
  buffer.writeln("        onTap: () => FocusScope.of(context).unfocus(),");
  buffer.writeln("        child: SafeArea(");
  buffer.writeln("          child: Stack(");
  buffer.writeln("            children: [");
  buffer.writeln("              Column(");
  buffer.writeln("                children: [");
  buffer.writeln("                  // Custom Wizard Progress Bar");
  buffer.writeln("                  Container(");
  buffer.writeln("                    width: double.infinity,");
  buffer.writeln("                    decoration: const BoxDecoration(");
  buffer.writeln("                      color: Colors.white,");
  buffer.writeln("                      border: Border(bottom: BorderSide(color: Color(0xFFE4E6F0), width: 1)),");
  buffer.writeln("                    ),");
  buffer.writeln("                    padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 20),");
  buffer.writeln("                    child: Center(");
  buffer.writeln("                      child: ConstrainedBox(");
  buffer.writeln("                        constraints: const BoxConstraints(maxWidth: 1000),");
  buffer.writeln("                        child: Row(");
  buffer.writeln("                          children: List.generate(total, (idx) {");
  buffer.writeln("                            final stepTitle = _getStepTitle(idx);");
  buffer.writeln("                            final isCompleted = idx < activeIdx;");
  buffer.writeln("                            final isActive = idx == activeIdx;");
  buffer.writeln("                            Color stepColor = isCompleted ? const Color(0xFF22C55E) : (isActive ? const Color(0xFF5B4FCF) : const Color(0xFFB0B4C8));");
  buffer.writeln("                            return Expanded(");
  buffer.writeln("                              child: Row(");
  buffer.writeln("                                children: [");
  buffer.writeln("                                  GestureDetector(");
  buffer.writeln("                                    onTap: () {");
  buffer.writeln("                                      if (idx <= activeIdx) {");
  buffer.writeln("                                        Get.toNamed('/' + _getStepId(idx));");
  buffer.writeln("                                      }");
  buffer.writeln("                                    },");
  buffer.writeln("                                    child: Tooltip(");
  buffer.writeln("                                      message: stepTitle,");
  buffer.writeln("                                      child: AnimatedContainer(");
  buffer.writeln("                                        duration: const Duration(milliseconds: 200),");
  buffer.writeln("                                        width: 32,");
  buffer.writeln("                                        height: 32,");
  buffer.writeln("                                        decoration: BoxDecoration(");
  buffer.writeln("                                          color: isActive ? const Color(0xFFEEECFD) : Colors.transparent,");
  buffer.writeln("                                          shape: BoxShape.circle,");
  buffer.writeln("                                          border: Border.all(");
  buffer.writeln("                                            color: stepColor,");
  buffer.writeln("                                            width: isActive ? 2.5 : 1.5,");
  buffer.writeln("                                          ),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                        child: Center(");
  buffer.writeln("                                          child: isCompleted");
  buffer.writeln("                                              ? const Icon(Icons.check_rounded, color: Color(0xFF22C55E), size: 16)");
  buffer.writeln("                                              : Text(");
  buffer.writeln("                                                  '\${idx + 1}',");
  buffer.writeln("                                                  style: GoogleFonts.poppins(");
  buffer.writeln("                                                    fontSize: 12,");
  buffer.writeln("                                                    fontWeight: isActive ? FontWeight.bold : FontWeight.w500,");
  buffer.writeln("                                                    color: isActive ? const Color(0xFF5B4FCF) : const Color(0xFF6B7280),");
  buffer.writeln("                                                  ),");
  buffer.writeln("                                                ),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ),");
  buffer.writeln("                                  if (!isMobile) ...[");
  buffer.writeln("                                    const SizedBox(width: 8),");
  buffer.writeln("                                    Flexible(");
  buffer.writeln("                                      child: Text(");
  buffer.writeln("                                        stepTitle,");
  buffer.writeln("                                        overflow: TextOverflow.ellipsis,");
  buffer.writeln("                                        style: GoogleFonts.poppins(");
  buffer.writeln("                                          fontSize: 12,");
  buffer.writeln("                                          fontWeight: isActive ? FontWeight.bold : FontWeight.w500,");
  buffer.writeln("                                          color: isActive ? const Color(0xFF1A1A2E) : const Color(0xFF6B7280),");
  buffer.writeln("                                        ),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                  ],");
  buffer.writeln("                                  if (idx < total - 1)");
  buffer.writeln("                                    Expanded(");
  buffer.writeln("                                      child: Container(");
  buffer.writeln("                                        height: 2,");
  buffer.writeln("                                        margin: const EdgeInsets.symmetric(horizontal: 8),");
  buffer.writeln("                                        color: isCompleted ? const Color(0xFF22C55E) : const Color(0xFFE4E6F0),");
  buffer.writeln("                                      ),");
  buffer.writeln("                                    ),");
  buffer.writeln("                                ],");
  buffer.writeln("                              ),");
  buffer.writeln("                            );");
  buffer.writeln("                          }),");
  buffer.writeln("                        ),");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                  ");
  buffer.writeln("                  Expanded(");
  buffer.writeln("                    child: SingleChildScrollView(");
  buffer.writeln("                      padding: EdgeInsets.symmetric(");
  buffer.writeln("                        horizontal: isMobile ? 16 : 32,");
  buffer.writeln("                        vertical: 24,");
  buffer.writeln("                      ),");
  buffer.writeln("                      child: Center(");
  buffer.writeln("                        child: ConstrainedBox(");
  buffer.writeln("                          constraints: const BoxConstraints(maxWidth: 800),");
  buffer.writeln("                          child: Container(");
  buffer.writeln("                            padding: EdgeInsets.all(isMobile ? 18 : 32),");
  buffer.writeln("                            decoration: BoxDecoration(");
  buffer.writeln("                              color: Colors.white,");
  buffer.writeln("                              borderRadius: BorderRadius.circular(24),");
  buffer.writeln("                              boxShadow: [");
  buffer.writeln("                                BoxShadow(");
  buffer.writeln("                                  color: const Color(0xFF5B4FCF).withValues(alpha: 0.06),");
  buffer.writeln("                                  blurRadius: 30,");
  buffer.writeln("                                  offset: const Offset(0, 8),");
  buffer.writeln("                                ),");
  buffer.writeln("                              ],");
  buffer.writeln("                              border: Border.all(color: const Color(0xFFE4E6F0).withValues(alpha: 0.5)),");
  buffer.writeln("                            ),");
  buffer.writeln("                            child: _buildFormContent(context, isMobile: isMobile),");
  buffer.writeln("                          ),");
  buffer.writeln("                        ),");
  buffer.writeln("                      ),");
  buffer.writeln("                    ),");
  buffer.writeln("                  ),");
  buffer.writeln("                ],");
  buffer.writeln("              ),");
  buffer.writeln("              _buildLoadingOverlay(),");
  buffer.writeln("            ],");
  buffer.writeln("          ),");
  buffer.writeln("        ),");
  buffer.writeln("      ),");
  buffer.writeln("    );");
}
