String generateDropdownSearchClass(
 ) {
   StringBuffer buffer = StringBuffer();
buffer.writeln("  import 'dart:async';	");
buffer.writeln("	import 'package:flutter/material.dart';	");
buffer.writeln("	import 'package:flutter/services.dart';	");
buffer.writeln("		");
buffer.writeln("	/// Reusable Key-Value Model	");
buffer.writeln("	class DropdownItem {	");
buffer.writeln("	  final String key;	");
buffer.writeln("	  final String value;	");
buffer.writeln("		");
buffer.writeln("	  DropdownItem({required this.key, required this.value});	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  String toString() => value;	");
buffer.writeln("	}	");
buffer.writeln("		");
buffer.writeln("	/// Label Position Enum	");
buffer.writeln("	enum LabelType { floating, top, left, inline }	");
buffer.writeln("		");
buffer.writeln("	/// Ultimate DropdownSearch Widget with all improvements	");
buffer.writeln("	class DropdownSearch<T> extends FormField<T> {	");
buffer.writeln("	  DropdownSearch({	");
buffer.writeln("	    super.key,	");
buffer.writeln("	    List<T> items = const [],	");
buffer.writeln("	    Future<List<T>>? futureItems,	");
buffer.writeln("	    String? label,	");
buffer.writeln("	    String? hint,	");
buffer.writeln("	    String Function(T)? itemAsString,	");
buffer.writeln("	    void Function(T?)? onChanged,	");
buffer.writeln("	    T? value,	");
buffer.writeln("	    LabelType labelType = LabelType.floating,	");
buffer.writeln("	    bool isMandatory = false,	");
buffer.writeln("	    FormFieldSetter<T>? onSaved,	");
buffer.writeln("	    FormFieldValidator<T>? validator,	");
buffer.writeln("	    bool showClearButton = true,	");
buffer.writeln("	    bool enabled = true,	");
buffer.writeln("	    bool enableKeyboardNavigation = true,	");
buffer.writeln("	    bool allowMultiSelect = false,	");
buffer.writeln("	    Color? dialogBackgroundColor,	");
buffer.writeln("	    Color? highlightColor,	");
buffer.writeln("	    double dialogWidthFactor = 0.9,	");
buffer.writeln("	    double dialogMaxWidth = 600,	");
buffer.writeln("	    double dialogMaxHeightFactor = 0.6,	");
buffer.writeln("	    BorderRadiusGeometry? dialogBorderRadius,	");
buffer.writeln("	    Widget? prefixIcon,	");
buffer.writeln("	    Widget? emptySearchWidget,	");
buffer.writeln("	    Widget Function(String)? noItemsBuilder,	");
buffer.writeln("	    String? searchHintText,	");
buffer.writeln("	    String? dialogTitle,	");
buffer.writeln("	    String? clearButtonTooltip,	");
buffer.writeln("	    String? selectAllText,	");
buffer.writeln("	    String? clearAllText,	");
buffer.writeln("	    InputDecoration? decoration,	");
buffer.writeln("	    TextStyle? labelStyle,	");
buffer.writeln("	    TextStyle? errorStyle,	");
buffer.writeln("	    TextStyle? selectedItemStyle,	");
buffer.writeln("	    EdgeInsetsGeometry? padding,	");
buffer.writeln("	    ScrollPhysics? scrollPhysics,	");
buffer.writeln("	    TextDirection? textDirection,	");
buffer.writeln("	    Duration searchDebounceDelay = const Duration(milliseconds: 300),	");
buffer.writeln("	  }) : super(	");
buffer.writeln("	          initialValue: value,	");
buffer.writeln("	          validator: validator ??	");
buffer.writeln("	              (isMandatory	");
buffer.writeln("	                  ? (val) => val == null	");
buffer.writeln("	                      ? 'Please select \${label ?? hint ?? 'an item'}'	");
buffer.writeln("	                      : null	");
buffer.writeln("	                  : null),	");
buffer.writeln("	          onSaved: onSaved,	");
buffer.writeln("	          builder: (FormFieldState<T> state) {	");
buffer.writeln("	            return Column(	");
buffer.writeln("	              crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	              children: [	");
buffer.writeln("	                _DropdownSearchBody<T>(	");
buffer.writeln("	                  items: items,	");
buffer.writeln("	                  futureItems: futureItems,	");
buffer.writeln("	                  label: label,	");
buffer.writeln("	                  hint: hint,	");
buffer.writeln("	                  itemAsString: itemAsString,	");
buffer.writeln("	                  value: state.value,	");
buffer.writeln("	                  onChanged: (val) {	");
buffer.writeln("	                    state.didChange(val);	");
buffer.writeln("	                    onChanged?.call(val);	");
buffer.writeln("	                  },	");
buffer.writeln("	                  labelType: labelType,	");
buffer.writeln("	                  isMandatory: isMandatory,	");
buffer.writeln("	                  showClearButton: showClearButton,	");
buffer.writeln("	                  enabled: enabled,	");
buffer.writeln("	                  dialogBackgroundColor: dialogBackgroundColor,	");
buffer.writeln("	                  highlightColor: highlightColor,	");
buffer.writeln("	                  dialogWidthFactor: dialogWidthFactor,	");
buffer.writeln("	                  dialogMaxWidth: dialogMaxWidth,	");
buffer.writeln("	                  dialogMaxHeightFactor: dialogMaxHeightFactor,	");
buffer.writeln("	                  dialogBorderRadius: dialogBorderRadius,	");
buffer.writeln("	                  prefixIcon: prefixIcon,	");
buffer.writeln("	                  emptySearchWidget: emptySearchWidget,	");
buffer.writeln("	                  noItemsBuilder: noItemsBuilder,	");
buffer.writeln("	                  searchHintText: searchHintText,	");
buffer.writeln("	                  dialogTitle: dialogTitle,	");
buffer.writeln("	                  clearButtonTooltip: clearButtonTooltip,	");
buffer.writeln("	                  selectAllText: selectAllText,	");
buffer.writeln("	                  clearAllText: clearAllText,	");
buffer.writeln("	                  decoration: decoration,	");
buffer.writeln("	                  labelStyle: labelStyle,	");
buffer.writeln("	                  errorText: state.errorText,	");
buffer.writeln("	                  errorStyle: errorStyle,	");
buffer.writeln("	                  selectedItemStyle: selectedItemStyle,	");
buffer.writeln("	                  padding: padding,	");
buffer.writeln("	                  scrollPhysics: scrollPhysics,	");
buffer.writeln("	                  textDirection: textDirection,	");
buffer.writeln("	                  enableKeyboardNavigation: enableKeyboardNavigation,	");
buffer.writeln("	                  allowMultiSelect: allowMultiSelect,	");
buffer.writeln("	                  searchDebounceDelay: searchDebounceDelay,	");
buffer.writeln("	                ),	");
buffer.writeln("	                if (state.hasError)	");
buffer.writeln("	                  Padding(	");
buffer.writeln("	                    padding: const EdgeInsets.only(top: 5, left: 8),	");
buffer.writeln("	                    child: Text(	");
buffer.writeln("	                      state.errorText!,	");
buffer.writeln("	                      style: errorStyle ??	");
buffer.writeln("	                          const TextStyle(color: Colors.red, fontSize: 12),	");
buffer.writeln("	                    ),	");
buffer.writeln("	                  ),	");
buffer.writeln("	              ],	");
buffer.writeln("	            );	");
buffer.writeln("	          },	");
buffer.writeln("	        );	");
buffer.writeln("	}	");
buffer.writeln("		");
buffer.writeln("	class _DropdownSearchBody<T> extends StatefulWidget {	");
buffer.writeln("	  final List<T> items;	");
buffer.writeln("	  final Future<List<T>>? futureItems;	");
buffer.writeln("	  final String? label;	");
buffer.writeln("	  final String? hint;	");
buffer.writeln("	  final String Function(T)? itemAsString;	");
buffer.writeln("	  final void Function(T?)? onChanged;	");
buffer.writeln("	  final T? value;	");
buffer.writeln("	  final LabelType labelType;	");
buffer.writeln("	  final bool isMandatory;	");
buffer.writeln("	  final bool showClearButton;	");
buffer.writeln("	  final bool enabled;	");
buffer.writeln("	  final Color? dialogBackgroundColor;	");
buffer.writeln("	  final Color? highlightColor;	");
buffer.writeln("	  final double dialogWidthFactor;	");
buffer.writeln("	  final double dialogMaxWidth;	");
buffer.writeln("	  final double dialogMaxHeightFactor;	");
buffer.writeln("	  final BorderRadiusGeometry? dialogBorderRadius;	");
buffer.writeln("	  final Widget? prefixIcon;	");
buffer.writeln("	  final Widget? emptySearchWidget;	");
buffer.writeln("	  final Widget Function(String)? noItemsBuilder;	");
buffer.writeln("	  final String? searchHintText;	");
buffer.writeln("	  final String? dialogTitle;	");
buffer.writeln("	  final String? clearButtonTooltip;	");
buffer.writeln("	  final String? selectAllText;	");
buffer.writeln("	  final String? clearAllText;	");
buffer.writeln("	  final InputDecoration? decoration;	");
buffer.writeln("	  final TextStyle? labelStyle;	");
buffer.writeln("	  final String? errorText;	");
buffer.writeln("	  final TextStyle? errorStyle;	");
buffer.writeln("	  final TextStyle? selectedItemStyle;	");
buffer.writeln("	  final EdgeInsetsGeometry? padding;	");
buffer.writeln("	  final ScrollPhysics? scrollPhysics;	");
buffer.writeln("	  final TextDirection? textDirection;	");
buffer.writeln("	  final bool enableKeyboardNavigation;	");
buffer.writeln("	  final bool allowMultiSelect;	");
buffer.writeln("	  final Duration searchDebounceDelay;	");
buffer.writeln("		");
buffer.writeln("	  const _DropdownSearchBody({	");
buffer.writeln("	    required this.items,	");
buffer.writeln("	    this.futureItems,	");
buffer.writeln("	    this.label,	");
buffer.writeln("	    this.hint,	");
buffer.writeln("	    this.itemAsString,	");
buffer.writeln("	    this.onChanged,	");
buffer.writeln("	    this.value,	");
buffer.writeln("	    this.labelType = LabelType.floating,	");
buffer.writeln("	    this.isMandatory = false,	");
buffer.writeln("	    this.showClearButton = true,	");
buffer.writeln("	    this.enabled = true,	");
buffer.writeln("	    this.dialogBackgroundColor,	");
buffer.writeln("	    this.highlightColor,	");
buffer.writeln("	    this.dialogWidthFactor = 0.9,	");
buffer.writeln("	    this.dialogMaxWidth = 600,	");
buffer.writeln("	    this.dialogMaxHeightFactor = 0.6,	");
buffer.writeln("	    this.dialogBorderRadius,	");
buffer.writeln("	    this.prefixIcon,	");
buffer.writeln("	    this.emptySearchWidget,	");
buffer.writeln("	    this.noItemsBuilder,	");
buffer.writeln("	    this.searchHintText,	");
buffer.writeln("	    this.dialogTitle,	");
buffer.writeln("	    this.clearButtonTooltip,	");
buffer.writeln("	    this.selectAllText = 'Select All',	");
buffer.writeln("	    this.clearAllText = 'Clear All',	");
buffer.writeln("	    this.decoration,	");
buffer.writeln("	    this.labelStyle,	");
buffer.writeln("	    this.errorText,	");
buffer.writeln("	    this.errorStyle,	");
buffer.writeln("	    this.selectedItemStyle,	");
buffer.writeln("	    this.padding,	");
buffer.writeln("	    this.scrollPhysics,	");
buffer.writeln("	    this.textDirection,	");
buffer.writeln("	    this.enableKeyboardNavigation = true,	");
buffer.writeln("	    this.allowMultiSelect = false,	");
buffer.writeln("	    this.searchDebounceDelay = const Duration(milliseconds: 300),	");
buffer.writeln("	  });	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  State<_DropdownSearchBody<T>> createState() => _DropdownSearchBodyState<T>();	");
buffer.writeln("	}	");
buffer.writeln("		");
buffer.writeln("	class _DropdownSearchBodyState<T> extends State<_DropdownSearchBody<T>> {	");
buffer.writeln("	  final TextEditingController _searchController = TextEditingController();	");
buffer.writeln("	  final FocusNode _searchFocusNode = FocusNode();	");
buffer.writeln("	  late List<T> _filteredItems;	");
buffer.writeln("	  int? _keyboardSelectedIndex;	");
buffer.writeln("	  Timer? _searchDebounce;	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  void initState() {	");
buffer.writeln("	    super.initState();	");
buffer.writeln("	    _filteredItems = widget.items;	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.futureItems != null) {	");
buffer.writeln("	      widget.futureItems!.then((items) {	");
buffer.writeln("	        if (mounted) setState(() {	");
buffer.writeln("	          _filteredItems = items;	");
buffer.writeln("	        });	");
buffer.writeln("	      });	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  void didUpdateWidget(covariant _DropdownSearchBody<T> oldWidget) {	");
buffer.writeln("	    super.didUpdateWidget(oldWidget);	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.items != oldWidget.items) {	");
buffer.writeln("	      _filteredItems = widget.items;	");
buffer.writeln("	      _searchController.clear();	");
buffer.writeln("	      _keyboardSelectedIndex = null;	");
buffer.writeln("	    }	");
buffer.writeln("	    	");
buffer.writeln("	    if (widget.futureItems != oldWidget.futureItems && widget.futureItems != null) {	");
buffer.writeln("	      widget.futureItems!.then((items) {	");
buffer.writeln("	        if (mounted) setState(() {	");
buffer.writeln("	          _filteredItems = items;	");
buffer.writeln("	        });	");
buffer.writeln("	      });	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  void dispose() {	");
buffer.writeln("	    _searchController.dispose();	");
buffer.writeln("	    _searchFocusNode.dispose();	");
buffer.writeln("	    _searchDebounce?.cancel();	");
buffer.writeln("	    super.dispose();	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _openSearchDialog() async {	");
buffer.writeln("	    if (!widget.enabled) return;	");
buffer.writeln("	    	");
buffer.writeln("	    _keyboardSelectedIndex = null;	");
buffer.writeln("	    	");
buffer.writeln("	    final selectedValue = await showDialog<T>(	");
buffer.writeln("	      context: context,	");
buffer.writeln("	      barrierDismissible: true,	");
buffer.writeln("	      builder: (context) => Dialog(	");
buffer.writeln("	        backgroundColor: Colors.transparent,	");
buffer.writeln("	        insetPadding: const EdgeInsets.all(20),	");
buffer.writeln("	        child: ConstrainedBox(	");
buffer.writeln("	          constraints: BoxConstraints(	");
buffer.writeln("	            maxWidth: widget.dialogMaxWidth,	");
buffer.writeln("	            maxHeight: MediaQuery.of(context).size.height * 	");
buffer.writeln("	                widget.dialogMaxHeightFactor,	");
buffer.writeln("	          ),	");
buffer.writeln("	          child: Material(	");
buffer.writeln("	            color: widget.dialogBackgroundColor ?? 	");
buffer.writeln("	                Theme.of(context).dialogBackgroundColor,	");
buffer.writeln("	            borderRadius: widget.dialogBorderRadius ?? 	");
buffer.writeln("	                BorderRadius.circular(12),	");
buffer.writeln("	            child: Directionality(	");
buffer.writeln("	              textDirection: widget.textDirection ?? 	");
buffer.writeln("	                  Directionality.of(context),	");
buffer.writeln("	              child: _buildDialogContent(),	");
buffer.writeln("	            ),	");
buffer.writeln("	          ),	");
buffer.writeln("	        ),	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("		");
buffer.writeln("	    if (selectedValue != null) {	");
buffer.writeln("	      widget.onChanged?.call(selectedValue);	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Widget _buildDialogContent() {	");
buffer.writeln("	    return KeyboardListener(	");
buffer.writeln("	      focusNode: FocusNode(),	");
buffer.writeln("	      onKeyEvent: widget.enableKeyboardNavigation ? _handleKeyEvent : null,	");
buffer.writeln("	      child: Padding(	");
buffer.writeln("	        padding: widget.padding ?? const EdgeInsets.all(20),	");
buffer.writeln("	        child: Column(	");
buffer.writeln("	          mainAxisSize: MainAxisSize.min,	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.stretch,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            // Header Row	");
buffer.writeln("	            Row(	");
buffer.writeln("	              mainAxisAlignment: MainAxisAlignment.spaceBetween,	");
buffer.writeln("	              children: [	");
buffer.writeln("	                Expanded(	");
buffer.writeln("	                  child: Text(	");
buffer.writeln("	                    widget.dialogTitle ?? 	");
buffer.writeln("	                        'Select \${widget.label ?? widget.hint ?? ""}',	");
buffer.writeln("	                    style: const TextStyle(	");
buffer.writeln("	                      fontSize: 18,	");
buffer.writeln("	                      fontWeight: FontWeight.bold,	");
buffer.writeln("	                    ),	");
buffer.writeln("	                    overflow: TextOverflow.ellipsis,	");
buffer.writeln("	                  ),	");
buffer.writeln("	                ),	");
buffer.writeln("	                IconButton(	");
buffer.writeln("	                  icon: const Icon(Icons.close),	");
buffer.writeln("	                  onPressed: () => Navigator.pop(context),	");
buffer.writeln("	                  tooltip: 'Close',	");
buffer.writeln("	                ),	");
buffer.writeln("	              ],	");
buffer.writeln("	            ),	");
buffer.writeln("	            	");
buffer.writeln("	            const SizedBox(height: 16),	");
buffer.writeln("	            	");
buffer.writeln("	            // Search Field	");
buffer.writeln("	            TextField(	");
buffer.writeln("	              controller: _searchController,	");
buffer.writeln("	              focusNode: _searchFocusNode,	");
buffer.writeln("	              decoration: InputDecoration(	");
buffer.writeln("	                labelText: widget.searchHintText ?? 'Search',	");
buffer.writeln("	                border: const OutlineInputBorder(),	");
buffer.writeln("	                suffixIcon: _searchController.text.isNotEmpty	");
buffer.writeln("	                    ? IconButton(	");
buffer.writeln("	                        icon: const Icon(Icons.clear),	");
buffer.writeln("	                        onPressed: () {	");
buffer.writeln("	                          _searchController.clear();	");
buffer.writeln("	                          setState(() {	");
buffer.writeln("	                            _filteredItems = widget.items;	");
buffer.writeln("	                            _keyboardSelectedIndex = null;	");
buffer.writeln("	                          });	");
buffer.writeln("	                        },	");
buffer.writeln("	                        tooltip: widget.clearButtonTooltip ?? 'Clear search',	");
buffer.writeln("	                      )	");
buffer.writeln("	                    : null,	");
buffer.writeln("	              ),	");
buffer.writeln("	              onChanged: _onSearchChanged,	");
buffer.writeln("	            ),	");
buffer.writeln("	            	");
buffer.writeln("	            const SizedBox(height: 16),	");
buffer.writeln("	            	");
buffer.writeln("	            // Bulk Actions (if multi-select enabled)	");
buffer.writeln("	            if (widget.allowMultiSelect) ...[	");
buffer.writeln("	              Row(	");
buffer.writeln("	                children: [	");
buffer.writeln("	                  TextButton(	");
buffer.writeln("	                    onPressed: _selectAll,	");
buffer.writeln("	                    child: Text(widget.selectAllText ?? 'Select All'),	");
buffer.writeln("	                  ),	");
buffer.writeln("	                  TextButton(	");
buffer.writeln("	                    onPressed: _clearAll,	");
buffer.writeln("	                    child: Text(widget.clearAllText ?? 'Clear All'),	");
buffer.writeln("	                  ),	");
buffer.writeln("	                ],	");
buffer.writeln("	              ),	");
buffer.writeln("	              const SizedBox(height: 8),	");
buffer.writeln("	            ],	");
buffer.writeln("	            	");
buffer.writeln("	            // List of Items	");
buffer.writeln("	            Expanded(	");
buffer.writeln("	              child: _filteredItems.isEmpty	");
buffer.writeln("	                  ? widget.noItemsBuilder?.call(_searchController.text) ?? 	");
buffer.writeln("	                      widget.emptySearchWidget ?? 	");
buffer.writeln("	                      const Center(child: Text('No items found'))	");
buffer.writeln("	                  : ListView.builder(	");
buffer.writeln("	                      shrinkWrap: true,	");
buffer.writeln("	                      physics: widget.scrollPhysics ?? 	");
buffer.writeln("	                          const ClampingScrollPhysics(),	");
buffer.writeln("	                      itemCount: _filteredItems.length,	");
buffer.writeln("	                      itemBuilder: (context, index) {	");
buffer.writeln("	                        final item = _filteredItems[index];	");
buffer.writeln("	                        final isSelected = widget.value == item;	");
buffer.writeln("	                        final isKeyboardSelected = 	");
buffer.writeln("	                            _keyboardSelectedIndex == index;	");
buffer.writeln("	                        	");
buffer.writeln("	                        return Material(	");
buffer.writeln("	                          color: isKeyboardSelected	");
buffer.writeln("	                              ? widget.highlightColor ?? 	");
buffer.writeln("	                                  Theme.of(context).highlightColor	");
buffer.writeln("	                              : Colors.transparent,	");
buffer.writeln("	                          child: ListTile(	");
buffer.writeln("	                            title: Text(	");
buffer.writeln("	                              widget.itemAsString?.call(item) ??	");
buffer.writeln("	                                  (item is DropdownItem 	");
buffer.writeln("	                                      ? item.value 	");
buffer.writeln("	                                      : item.toString()),	");
buffer.writeln("	                              overflow: TextOverflow.ellipsis,	");
buffer.writeln("	                              style: isSelected 	");
buffer.writeln("	                                  ? widget.selectedItemStyle ?? 	");
buffer.writeln("	                                      TextStyle(	");
buffer.writeln("	                                        color: Theme.of(context).primaryColor,	");
buffer.writeln("	                                        fontWeight: FontWeight.bold,	");
buffer.writeln("	                                      )	");
buffer.writeln("	                                  : null,	");
buffer.writeln("	                            ),	");
buffer.writeln("	                            tileColor: isSelected	");
buffer.writeln("	                                ? Theme.of(context)	");
buffer.writeln("	                                    .primaryColor	");
buffer.writeln("	                                    .withOpacity(0.1)	");
buffer.writeln("	                                : null,	");
buffer.writeln("	                            onTap: () => Navigator.pop(context, item),	");
buffer.writeln("	                          ),	");
buffer.writeln("	                        );	");
buffer.writeln("	                      },	");
buffer.writeln("	                    ),	");
buffer.writeln("	            ),	");
buffer.writeln("	          ],	");
buffer.writeln("	        ),	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _onSearchChanged(String value) {	");
buffer.writeln("	    if (_searchDebounce?.isActive ?? false) _searchDebounce?.cancel();	");
buffer.writeln("	    	");
buffer.writeln("	    _searchDebounce = Timer(widget.searchDebounceDelay, () {	");
buffer.writeln("	      if (mounted) {	");
buffer.writeln("	        setState(() {	");
buffer.writeln("	          _filteredItems = widget.items	");
buffer.writeln("	              .where((item) => (widget.itemAsString?.call(item) ??	");
buffer.writeln("	                      (item is DropdownItem ? item.value : item.toString()))	");
buffer.writeln("	                  .toLowerCase()	");
buffer.writeln("	                  .contains(value.toLowerCase()))	");
buffer.writeln("	              .toList();	");
buffer.writeln("	          _keyboardSelectedIndex = null;	");
buffer.writeln("	        });	");
buffer.writeln("	      }	");
buffer.writeln("	    });	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _handleKeyEvent(KeyEvent event) {	");
buffer.writeln("	    if (event is KeyDownEvent) {	");
buffer.writeln("	      if (event.logicalKey == LogicalKeyboardKey.arrowDown) {	");
buffer.writeln("	        setState(() {	");
buffer.writeln("	          _keyboardSelectedIndex = _keyboardSelectedIndex == null	");
buffer.writeln("	              ? 0	");
buffer.writeln("	              : (_keyboardSelectedIndex! + 1) % _filteredItems.length;	");
buffer.writeln("	        });	");
buffer.writeln("	      } else if (event.logicalKey == LogicalKeyboardKey.arrowUp) {	");
buffer.writeln("	        setState(() {	");
buffer.writeln("	          _keyboardSelectedIndex = _keyboardSelectedIndex == null	");
buffer.writeln("	              ? _filteredItems.length - 1	");
buffer.writeln("	              : (_keyboardSelectedIndex! - 1) % _filteredItems.length;	");
buffer.writeln("	        });	");
buffer.writeln("	      } else if (event.logicalKey == LogicalKeyboardKey.enter &&	");
buffer.writeln("	          _keyboardSelectedIndex != null) {	");
buffer.writeln("	        Navigator.pop(context, _filteredItems[_keyboardSelectedIndex!]);	");
buffer.writeln("	      }	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _selectAll() {	");
buffer.writeln("	    // Implementation depends on your multi-select logic	");
buffer.writeln("	    // This is just a placeholder	");
buffer.writeln("	    if (_filteredItems.isNotEmpty) {	");
buffer.writeln("	      Navigator.pop(context, _filteredItems.first);	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  void _clearAll() {	");
buffer.writeln("	    Navigator.pop(context, null);	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Widget _buildLabel(String? text, bool isMandatory) {	");
buffer.writeln("	    if (widget.label == null) return const SizedBox.shrink();	");
buffer.writeln("	    	");
buffer.writeln('    final theme = Theme.of(context);');
buffer.writeln('    final TextStyle baseStyle = theme.textTheme.bodyMedium!.copyWith(');
buffer.writeln('      fontWeight: FontWeight.w400,');
buffer.writeln('    );');
buffer.writeln('    final Color requiredMarkColor = theme.colorScheme.error;');
buffer.writeln('');

buffer.writeln("	    return RichText(	");
buffer.writeln("	      text: TextSpan(	");
buffer.writeln("	        text: text ?? '',	");
buffer.writeln('        style: baseStyle,');
buffer.writeln("	        children: isMandatory	");
buffer.writeln("	            ? [	");
buffer.writeln("	                const TextSpan(	");
buffer.writeln("	                  text: ' *',	");
buffer.writeln('                  style: baseStyle.copyWith(color: requiredMarkColor),');
buffer.writeln("	                ),	");
buffer.writeln("	              ]	");
buffer.writeln("	            : [],	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  Widget build(BuildContext context) {	");
buffer.writeln("	    final effectiveLabelText = widget.label ?? widget.hint;	");
buffer.writeln("	    final effectiveDecoration = (widget.decoration ?? InputDecoration(	");
buffer.writeln("	      label: widget.labelType == LabelType.floating	");
buffer.writeln("	          ? _buildLabel(effectiveLabelText, widget.isMandatory)	");
buffer.writeln("	          : null,	");
buffer.writeln("	      border: const OutlineInputBorder(),	");
buffer.writeln("	      suffixIcon: widget.showClearButton && widget.value != null	");
buffer.writeln("	          ? IconButton(	");
buffer.writeln("	              icon: const Icon(Icons.clear, size: 20),	");
buffer.writeln("	              onPressed: () => widget.onChanged?.call(null),	");
buffer.writeln("	              tooltip: widget.clearButtonTooltip ?? 'Clear selection',	");
buffer.writeln("	            )	");
buffer.writeln("	          : const Icon(Icons.arrow_drop_down),	");
buffer.writeln("	      hintText: widget.value == null ? widget.hint : null,	");
buffer.writeln("	      prefixIcon: widget.prefixIcon,	");
buffer.writeln("	      enabled: widget.enabled,	");
buffer.writeln("	    )).copyWith(errorText: widget.errorText);	");
buffer.writeln("		");
buffer.writeln("	    Widget dropdownContent = GestureDetector(	");
buffer.writeln("	      behavior: HitTestBehavior.opaque,	");
buffer.writeln("	      onTap: _openSearchDialog,	");
buffer.writeln("	      child: InputDecorator(	");
buffer.writeln("	        decoration: effectiveDecoration,	");
buffer.writeln("	        child: Text(	");
buffer.writeln("	          widget.value != null	");
buffer.writeln("	              ? (widget.itemAsString?.call(widget.value!) ??	");
buffer.writeln("	                  (widget.value is DropdownItem 	");
buffer.writeln("	                      ? (widget.value as DropdownItem).value 	");
buffer.writeln("	                      : widget.value.toString()))	");
buffer.writeln("	              : '',	");
buffer.writeln("	          overflow: TextOverflow.ellipsis,	");
buffer.writeln("	          style: !widget.enabled	");
buffer.writeln("	              ? TextStyle(color: Theme.of(context).disabledColor)	");
buffer.writeln("	              : null,	");
buffer.writeln("	        ),	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("		");
buffer.writeln("	    switch (widget.labelType) {	");
buffer.writeln("	      case LabelType.floating:	");
buffer.writeln("	        return dropdownContent;	");
buffer.writeln("	      case LabelType.top:	");
buffer.writeln("	        return Column(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            _buildLabel(effectiveLabelText, widget.isMandatory),	");
buffer.writeln("	            const SizedBox(height: 8),	");
buffer.writeln("	            dropdownContent,	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	      case LabelType.left:	");
buffer.writeln("	        return Row(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            Padding(	");
buffer.writeln("	              padding: const EdgeInsets.only(top: 16),	");
buffer.writeln("	              child: _buildLabel(effectiveLabelText, widget.isMandatory),	");
buffer.writeln("	            ),	");
buffer.writeln("	            const SizedBox(width: 8),	");
buffer.writeln("	            Expanded(child: dropdownContent),	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	      case LabelType.inline:	");
buffer.writeln("	        return Row(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.center,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            _buildLabel(effectiveLabelText, widget.isMandatory),	");
buffer.writeln("	            const SizedBox(width: 8),	");
buffer.writeln("	            Expanded(child: dropdownContent),	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	    }	");
buffer.writeln("	  }	");
buffer.writeln("	}	");
buffer.writeln("		");
 return buffer.toString().replaceAll('\u00A0', ' ');
}

