
String generateMultiSelectClass(
 ) {
   StringBuffer buffer = StringBuffer();
buffer.writeln(r"	import 'package:flutter/foundation.dart';	");
buffer.writeln(r"	import 'package:flutter/material.dart';	");
buffer.writeln(r"		");
buffer.writeln(r"	enum LabelPosition { floating, top, left, inline }	");
buffer.writeln(r"		");
buffer.writeln(r"	class MultiSelectDropdown<T> extends StatefulWidget {	");
buffer.writeln(r"	  final String? label;	");
buffer.writeln(r"	  final List<T> items;	");
buffer.writeln(r"	  final List<T> selectedItems;	");
buffer.writeln(r"	  final void Function(List<T>) onChanged;	");
buffer.writeln(r"	  final String Function(T) itemLabel;	");
buffer.writeln(r"	  final bool isMandatory;	");
buffer.writeln(r"	  final String? helperText;	");
buffer.writeln(r"	  final String? errorText;	");
buffer.writeln(r"	  final LabelPosition labelPosition;	");
buffer.writeln(r"	  final bool readOnly;	");
buffer.writeln(r"	  final double width;	");
buffer.writeln(r"	  final double? dialogWidth;	");
buffer.writeln(r"	  final double? dialogHeight;	");
buffer.writeln(r"	  final String? dialogTitle;	");
buffer.writeln(r"	  final String cancelButtonText;	");
buffer.writeln(r"	  final String confirmButtonText;	");
buffer.writeln(r"	  final String searchHintText;	");
buffer.writeln(r"	  final String emptyItemsText;	");
buffer.writeln(r"	  final String placeholderText;	");
buffer.writeln(r"	  final bool showSearch;	");
buffer.writeln(r"	  final Color? chipColor;	");
buffer.writeln(r"	  final Color? chipTextColor;	");
buffer.writeln(r"	  final InputBorder? border;	");
buffer.writeln(r"	  final EdgeInsetsGeometry? padding;	");
buffer.writeln(r"	  final TextStyle? labelStyle;	");
buffer.writeln(r"	  final TextStyle? selectedItemStyle;	");
buffer.writeln(r"	  final TextStyle? placeholderStyle;	");
buffer.writeln(r"	  final bool showChips;	");
buffer.writeln(r"		");
buffer.writeln(r"	  const MultiSelectDropdown({	");
buffer.writeln(r"	    super.key,	");
buffer.writeln(r"	    this.label,	");
buffer.writeln(r"	    required this.items,	");
buffer.writeln(r"	    required this.selectedItems,	");
buffer.writeln(r"	    required this.onChanged,	");
buffer.writeln(r"	    required this.itemLabel,	");
buffer.writeln(r"	    this.isMandatory = false,	");
buffer.writeln(r"	    this.helperText,	");
buffer.writeln(r"	    this.errorText,	");
buffer.writeln(r"	    this.labelPosition = LabelPosition.top,	");
buffer.writeln(r"	    this.readOnly = false,	");
buffer.writeln(r"	    this.width = double.infinity,	");
buffer.writeln(r"	    this.dialogWidth,	");
buffer.writeln(r"	    this.dialogHeight,	");
buffer.writeln(r"	    this.dialogTitle,	");
buffer.writeln(r"	    this.cancelButtonText = 'Cancel',	");
buffer.writeln(r"	    this.confirmButtonText = 'OK',	");
buffer.writeln(r"	    this.searchHintText = 'Search...',	");
buffer.writeln(r"	    this.emptyItemsText = 'No items found',	");
buffer.writeln(r"	    this.placeholderText = 'Select items',	");
buffer.writeln(r"	    this.showSearch = true,	");
buffer.writeln(r"	    this.chipColor,	");
buffer.writeln(r"	    this.chipTextColor,	");
buffer.writeln(r"	    this.border,	");
buffer.writeln(r"	    this.padding,	");
buffer.writeln(r"	    this.labelStyle,	");
buffer.writeln(r"	    this.selectedItemStyle,	");
buffer.writeln(r"	    this.placeholderStyle,	");
buffer.writeln(r"	    this.showChips = true,	");
buffer.writeln(r"	  });	");
buffer.writeln(r"		");
buffer.writeln(r"	  @override	");
buffer.writeln(r"	  State<MultiSelectDropdown<T>> createState() => _MultiSelectDropdownState<T>();	");
buffer.writeln(r"	}	");
buffer.writeln(r"		");
buffer.writeln(r"	class _MultiSelectDropdownState<T> extends State<MultiSelectDropdown<T>> {	");
buffer.writeln(r"	  late List<T> _selectedItems;	");
buffer.writeln(r"	  String _searchText = '';	");
buffer.writeln(r"	  final FocusNode _focusNode = FocusNode();	");
buffer.writeln(r"	  bool _isFocused = false;	");
buffer.writeln(r"		");
buffer.writeln(r"	  @override	");
buffer.writeln(r"	  void initState() {	");
buffer.writeln(r"	    super.initState();	");
buffer.writeln(r"	    _selectedItems = [...widget.selectedItems];	");
buffer.writeln(r"	    _focusNode.addListener(_onFocusChange);	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  @override	");
buffer.writeln(r"	  void dispose() {	");
buffer.writeln(r"	    _focusNode.removeListener(_onFocusChange);	");
buffer.writeln(r"	    _focusNode.dispose();	");
buffer.writeln(r"	    super.dispose();	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  void _onFocusChange() {	");
buffer.writeln(r"	    setState(() {	");
buffer.writeln(r"	      _isFocused = _focusNode.hasFocus;	");
buffer.writeln(r"	    });	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  @override	");
buffer.writeln(r"	  void didUpdateWidget(covariant MultiSelectDropdown<T> oldWidget) {	");
buffer.writeln(r"	    super.didUpdateWidget(oldWidget);	");
buffer.writeln(r"	    if (widget.selectedItems != oldWidget.selectedItems) {	");
buffer.writeln(r"	      _selectedItems = [...widget.selectedItems];	");
buffer.writeln(r"	    }	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  Future<void> _openMultiSelectDialog() async {	");
buffer.writeln(r"	    if (widget.readOnly) return;	");
buffer.writeln(r"		");
buffer.writeln(r"	    final List<T> initialSelectedItems = [..._selectedItems];	");
buffer.writeln(r"	    _searchText = '';	");
buffer.writeln(r"		");
buffer.writeln(r"	    final List<T>? selected = await showDialog<List<T>>(	");
buffer.writeln(r"	      context: context,	");
buffer.writeln(r"	      builder: (context) {	");
buffer.writeln(r"	        List<T> filteredItems = widget.items;	");
buffer.writeln(r"	        return StatefulBuilder(	");
buffer.writeln(r"	          builder: (context, setStateDialog) {	");
buffer.writeln(r"	            void filterItems(String text) {	");
buffer.writeln(r"	              setStateDialog(() {	");
buffer.writeln(r"	                _searchText = text;	");
buffer.writeln(r"	                filteredItems =	");
buffer.writeln(r"	                    widget.items	");
buffer.writeln(r"	                        .where(	");
buffer.writeln(r"	                          (item) => widget	");
buffer.writeln(r"	                              .itemLabel(item)	");
buffer.writeln(r"	                              .toLowerCase()	");
buffer.writeln(r"	                              .contains(text.toLowerCase()),	");
buffer.writeln(r"	                        )	");
buffer.writeln(r"	                        .toList();	");
buffer.writeln(r"	              });	");
buffer.writeln(r"	            }	");
buffer.writeln(r"		");
buffer.writeln(r"	            return Dialog(	");
buffer.writeln(r"	              backgroundColor: Theme.of(context).dialogBackgroundColor,	");
buffer.writeln(r"	              insetPadding: const EdgeInsets.all(20),	");
buffer.writeln(r"	              shape: RoundedRectangleBorder(	");
buffer.writeln(r"	                borderRadius: BorderRadius.circular(16),	");
buffer.writeln(r"	              ),	");
buffer.writeln(r"	              child: ConstrainedBox(	");
buffer.writeln(r"	                constraints: BoxConstraints(	");
buffer.writeln(r"	                  maxWidth: widget.dialogWidth ?? 400,	");
buffer.writeln(r"	                  maxHeight:	");
buffer.writeln(r"	                      widget.dialogHeight ??	");
buffer.writeln(r"	                      MediaQuery.of(context).size.height * 0.7,	");
buffer.writeln(r"	                ),	");
buffer.writeln(r"	                child: Column(	");
buffer.writeln(r"	                  mainAxisSize: MainAxisSize.min,	");
buffer.writeln(r"	                  children: [	");
buffer.writeln(r"	                    Padding(	");
buffer.writeln(r"	                      padding: const EdgeInsets.fromLTRB(24, 20, 24, 0),	");
buffer.writeln(r"	                      child: Column(	");
buffer.writeln(r"	                        crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln(r"	                        children: [	");
buffer.writeln(r"	                          Text(	");
buffer.writeln(r"	                            widget.dialogTitle ?? widget.label ?? 'Select',	");
buffer.writeln(r"	                            style: Theme.of(context).textTheme.titleLarge,	");
buffer.writeln(r"	                          ),	");
buffer.writeln(r"	                          if (widget.showSearch) ...[	");
buffer.writeln(r"	                            const SizedBox(height: 16),	");
buffer.writeln(r"	                            TextField(	");
buffer.writeln(r"	                              decoration: InputDecoration(	");
buffer.writeln(r"	                                hintText: widget.searchHintText,	");
buffer.writeln(r"	                                prefixIcon: const Icon(Icons.search),	");
buffer.writeln(r"	                                border: OutlineInputBorder(	");
buffer.writeln(r"	                                  borderRadius: BorderRadius.circular(8),	");
buffer.writeln(r"	                                ),	");
buffer.writeln(r"	                                contentPadding: const EdgeInsets.symmetric(	");
buffer.writeln(r"	                                  vertical: 12,	");
buffer.writeln(r"	                                  horizontal: 16,	");
buffer.writeln(r"	                                ),	");
buffer.writeln(r"	                              ),	");
buffer.writeln(r"	                              onChanged: filterItems,	");
buffer.writeln(r"	                              autofocus: true,	");
buffer.writeln(r"	                            ),	");
buffer.writeln(r"	                          ],	");
buffer.writeln(r"	                        ],	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                    const SizedBox(height: 16),	");
buffer.writeln(r"	                    Expanded(	");
buffer.writeln(r"	                      child:	");
buffer.writeln(r"	                          filteredItems.isEmpty	");
buffer.writeln(r"	                              ? Center(	");
buffer.writeln(r"	                                child: Padding(	");
buffer.writeln(r"	                                  padding: const EdgeInsets.all(16),	");
buffer.writeln(r"	                                  child: Text(widget.emptyItemsText),	");
buffer.writeln(r"	                                ),	");
buffer.writeln(r"	                              )	");
buffer.writeln(r"	                              : ListView.builder(	");
buffer.writeln(r"	                                padding: const EdgeInsets.symmetric(	");
buffer.writeln(r"	                                  horizontal: 8,	");
buffer.writeln(r"	                                ),	");
buffer.writeln(r"	                                itemCount: filteredItems.length,	");
buffer.writeln(r"	                                itemBuilder: (context, index) {	");
buffer.writeln(r"	                                  final item = filteredItems[index];	");
buffer.writeln(r"	                                  return CheckboxListTile(	");
buffer.writeln(r"	                                    title: Text(	");
buffer.writeln(r"	                                      widget.itemLabel(item),	");
buffer.writeln(r"	                                      style:	");
buffer.writeln(r"	                                          Theme.of(context).textTheme.bodyLarge,	");
buffer.writeln(r"	                                    ),	");
buffer.writeln(r"	                                    value: _selectedItems.contains(item),	");
buffer.writeln(r"	                                    onChanged: (bool? checked) {	");
buffer.writeln(r"	                                      setStateDialog(() {	");
buffer.writeln(r"	                                        if (checked == true) {	");
buffer.writeln(r"	                                          _selectedItems.add(item);	");
buffer.writeln(r"	                                        } else {	");
buffer.writeln(r"	                                          _selectedItems.remove(item);	");
buffer.writeln(r"	                                        }	");
buffer.writeln(r"	                                      });	");
buffer.writeln(r"	                                    },	");
buffer.writeln(r"	                                  );	");
buffer.writeln(r"	                                },	");
buffer.writeln(r"	                              ),	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                    Padding(	");
buffer.writeln(r"	                      padding: const EdgeInsets.all(16),	");
buffer.writeln(r"	                      child: Row(	");
buffer.writeln(r"	                        mainAxisAlignment: MainAxisAlignment.end,	");
buffer.writeln(r"	                        children: [	");
buffer.writeln(r"	                          TextButton(	");
buffer.writeln(r"	                            onPressed:	");
buffer.writeln(r"	                                () => Navigator.pop(	");
buffer.writeln(r"	                                  context,	");
buffer.writeln(r"	                                  initialSelectedItems,	");
buffer.writeln(r"	                                ),	");
buffer.writeln(r"	                            child: Text(widget.cancelButtonText),	");
buffer.writeln(r"	                          ),	");
buffer.writeln(r"	                          const SizedBox(width: 8),	");
buffer.writeln(r"	                          ElevatedButton(	");
buffer.writeln(r"	                            onPressed:	");
buffer.writeln(r"	                                () => Navigator.pop(context, _selectedItems),	");
buffer.writeln(r"	                            child: Text(widget.confirmButtonText),	");
buffer.writeln(r"	                          ),	");
buffer.writeln(r"	                        ],	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                  ],	");
buffer.writeln(r"	                ),	");
buffer.writeln(r"	              ),	");
buffer.writeln(r"	            );	");
buffer.writeln(r"	          },	");
buffer.writeln(r"	        );	");
buffer.writeln(r"	      },	");
buffer.writeln(r"	    );	");
buffer.writeln(r"		");
buffer.writeln(r"	    if (selected != null && !listEquals(selected, initialSelectedItems)) {	");
buffer.writeln(r"	      setState(() {	");
buffer.writeln(r"	        _selectedItems = selected;	");
buffer.writeln(r"	      });	");
buffer.writeln(r"	      widget.onChanged(_selectedItems);	");
buffer.writeln(r"	    }	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  Widget _buildLabel() {	");
buffer.writeln(r"	    if (widget.label == null) return const SizedBox.shrink();	");
buffer.writeln(r"		");
buffer.writeln(r"	    return Padding(	");
buffer.writeln(r"	      padding: const EdgeInsets.only(bottom: 4),	");
buffer.writeln(r"	      child: RichText(	");
buffer.writeln(r"	        text: TextSpan(	");
buffer.writeln(r"	          text: widget.label!,	");
buffer.writeln(r"	          style:	");
buffer.writeln(r"	              widget.labelStyle ??	");
buffer.writeln(r"	              Theme.of(context).textTheme.titleMedium?.copyWith(	");
buffer.writeln(r"	                color:	");
buffer.writeln(r"	                    _isFocused ? Theme.of(context).colorScheme.primary : null,	");
buffer.writeln(r"	              ),	");
buffer.writeln(r"	          children: [	");
buffer.writeln(r"	            if (widget.isMandatory)	");
buffer.writeln(r"	              const TextSpan(text: ' *', style: TextStyle(color: Colors.red)),	");
buffer.writeln(r"	          ],	");
buffer.writeln(r"	        ),	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Widget _buildSelectedItems() {	");
buffer.writeln("	    if (_selectedItems.isEmpty) {	");
buffer.writeln("	      return Text(	");
buffer.writeln("	        widget.placeholderText,	");
buffer.writeln("	        style:	");
buffer.writeln("	            widget.placeholderStyle ??	");
buffer.writeln("	            Theme.of(context).textTheme.bodyMedium?.copyWith(	");
buffer.writeln("	              color: Theme.of(context).hintColor,	");
buffer.writeln("	            ),	");
buffer.writeln("	      );	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    if (!widget.showChips) {	");
buffer.writeln("	      return Text(	");
buffer.writeln("	        _selectedItems.map(widget.itemLabel).join(', '),	");
buffer.writeln("	        style:	");
buffer.writeln("	            widget.selectedItemStyle ?? Theme.of(context).textTheme.bodyMedium,	");
buffer.writeln("	        maxLines: 1,	");
buffer.writeln("	        overflow: TextOverflow.ellipsis,	");
buffer.writeln("	      );	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    return Wrap(	");
buffer.writeln("	      spacing: 8,	");
buffer.writeln("	      runSpacing: 4,	");
buffer.writeln("	      children:	");
buffer.writeln("	          _selectedItems.map((item) {	");
buffer.writeln("	            return Chip(	");
buffer.writeln("	              label: Text(	");
buffer.writeln("	                widget.itemLabel(item),	");
buffer.writeln("	                style: TextStyle(	");
buffer.writeln("	                  color:	");
buffer.writeln("	                      widget.chipTextColor ??	");
buffer.writeln("	                      Theme.of(context).colorScheme.onPrimaryContainer,	");
buffer.writeln("	                ),	");
buffer.writeln("	              ),	");
buffer.writeln("	              backgroundColor:	");
buffer.writeln("	                  widget.chipColor ??	");
buffer.writeln("	                  Theme.of(context).colorScheme.primaryContainer,	");
buffer.writeln("	              deleteIcon: const Icon(Icons.cancel, size: 18),	");
buffer.writeln("	              onDeleted:	");
buffer.writeln("	                  widget.readOnly	");
buffer.writeln("	                      ? null	");
buffer.writeln("	                      : () {	");
buffer.writeln("	                        setState(() {	");
buffer.writeln("	                          _selectedItems.remove(item);	");
buffer.writeln("	                        });	");
buffer.writeln("	                        widget.onChanged(_selectedItems);	");
buffer.writeln("	                      },	");
buffer.writeln("	            );	");
buffer.writeln("	          }).toList(),	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  Widget _buildField() {	");
buffer.writeln("	    final border =	");
buffer.writeln("	        widget.border ??	");
buffer.writeln("	        OutlineInputBorder(	");
buffer.writeln("	          borderRadius: BorderRadius.circular(12),	");
buffer.writeln("	          borderSide: BorderSide(	");
buffer.writeln("	            color:	");
buffer.writeln("	                _isFocused	");
buffer.writeln("	                    ? Theme.of(context).colorScheme.primary	");
buffer.writeln("	                    : Colors.grey.shade400,	");
buffer.writeln("	            width: 1.2,	");
buffer.writeln("	          ),	");
buffer.writeln("	        );	");
buffer.writeln("		");
buffer.writeln("	    return GestureDetector(	");
buffer.writeln("	      onTap: widget.readOnly ? null : _openMultiSelectDialog,	");
buffer.writeln("	      behavior: HitTestBehavior.opaque,	");
buffer.writeln("	      child: Focus(	");
buffer.writeln("	        focusNode: _focusNode,	");
buffer.writeln("	        child: AnimatedContainer(	");
buffer.writeln("	          duration: const Duration(milliseconds: 200),	");
buffer.writeln("	          curve: Curves.easeInOut,	");
buffer.writeln("	          width: widget.width,	");
buffer.writeln("	          padding:	");
buffer.writeln("	              widget.padding ??	");
buffer.writeln("	              const EdgeInsets.symmetric(horizontal: 16, vertical: 14),	");
buffer.writeln("	          decoration: BoxDecoration(	");
buffer.writeln("	            color:	");
buffer.writeln("	                widget.readOnly	");
buffer.writeln("	                    ? Theme.of(context).disabledColor.withValues(alpha:0.1)	");
buffer.writeln("	                    : Theme.of(context).colorScheme.surface,	");
buffer.writeln("	            border: Border.all(	");
buffer.writeln("	              color:	");
buffer.writeln("	                  _isFocused	");
buffer.writeln("	                      ? Theme.of(context).colorScheme.primary	");
buffer.writeln("	                      : Theme.of(context).dividerColor,	");
buffer.writeln("	              width: 1.5,	");
buffer.writeln("	            ),	");
buffer.writeln("	            borderRadius: BorderRadius.circular(8),	");
buffer.writeln("	            boxShadow:	");
buffer.writeln("	                _isFocused	");
buffer.writeln("	                    ? [	");
buffer.writeln("	                      BoxShadow(	");
buffer.writeln("	                        color: Theme.of(	");
buffer.writeln("	                          context,	");
buffer.writeln("	                        ).colorScheme.primary.withValues(alpha:0.1),	");
buffer.writeln("	                        blurRadius: 4,	");
buffer.writeln("	                        spreadRadius: 1,	");
buffer.writeln("	                        offset: const Offset(0, 2),	");
buffer.writeln("	                      ),	");
buffer.writeln("	                    ]	");
buffer.writeln("	                    : null,	");
buffer.writeln("	          ),	");
buffer.writeln("	          child: Semantics(	");
buffer.writeln("	            button: true,	");
buffer.writeln("	            enabled: !widget.readOnly,	");
buffer.writeln("	            child: Row(	");
buffer.writeln("	              mainAxisAlignment: MainAxisAlignment.spaceBetween,	");
buffer.writeln("	              children: [	");
buffer.writeln("	                Expanded(	");
buffer.writeln("	                  child: Padding(	");
buffer.writeln("	                    padding: const EdgeInsets.only(right: 8),	");
buffer.writeln("	                    child: _buildSelectedItems(),	");
buffer.writeln("	                  ),	");
buffer.writeln("	                ),	");
buffer.writeln("	                Icon(	");
buffer.writeln("	                  Icons.arrow_drop_down,	");
buffer.writeln("	                  size: 24,	");
buffer.writeln("	                  color:	");
buffer.writeln("	                      widget.readOnly	");
buffer.writeln("	                          ? Theme.of(context).disabledColor	");
buffer.writeln("	                          : Theme.of(context).colorScheme.onSurface,	");
buffer.writeln("	                ),	");
buffer.writeln("	              ],	");
buffer.writeln("	            ),	");
buffer.writeln("	          ),	");
buffer.writeln("	        ),	");
buffer.writeln("	      ),	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("		");
buffer.writeln("	  @override	");
buffer.writeln("	  Widget build(BuildContext context) {	");
buffer.writeln("	    Widget labeledField;	");
buffer.writeln("		");
buffer.writeln("	    switch (widget.labelPosition) {	");
buffer.writeln("	      case LabelPosition.top:	");
buffer.writeln("	        labeledField = Column(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [_buildLabel(), const SizedBox(height: 4), _buildField()],	");
buffer.writeln("	        );	");
buffer.writeln("	        break;	");
buffer.writeln("	      case LabelPosition.left:	");
buffer.writeln("	        labeledField = Row(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            SizedBox(	");
buffer.writeln("	              width: 100,	");
buffer.writeln("	              child: Padding(	");
buffer.writeln("	                padding: const EdgeInsets.only(top: 16),	");
buffer.writeln("	                child: _buildLabel(),	");
buffer.writeln("	              ),	");
buffer.writeln("	            ),	");
buffer.writeln("	            const SizedBox(width: 12),	");
buffer.writeln("	            Expanded(child: _buildField()),	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	        break;	");
buffer.writeln("	      case LabelPosition.inline:	");
buffer.writeln("	        labeledField = Row(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.center,	");
buffer.writeln("	          children: [	");
buffer.writeln("	            _buildLabel(),	");
buffer.writeln("	            const SizedBox(width: 12),	");
buffer.writeln("	            Expanded(child: _buildField()),	");
buffer.writeln("	          ],	");
buffer.writeln("	        );	");
buffer.writeln("	        break;	");
buffer.writeln("	      case LabelPosition.floating:	");
buffer.writeln("	      default:	");
buffer.writeln("	        labeledField = Column(	");
buffer.writeln("	          crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	          children: [_buildField()],	");
buffer.writeln("	        );	");
buffer.writeln("	    }	");
buffer.writeln("		");
buffer.writeln("	    return Column(	");
buffer.writeln("	      crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln("	      children: [	");
buffer.writeln("	        labeledField,	");
buffer.writeln("	        if (widget.helperText != null)	");
buffer.writeln("	          Padding(	");
buffer.writeln("	            padding: const EdgeInsets.only(top: 4, left: 12),	");
buffer.writeln("	            child: Text(	");
buffer.writeln("	              widget.helperText!,	");
buffer.writeln("	              style: Theme.of(context).textTheme.bodySmall?.copyWith(	");
buffer.writeln("	                color: Theme.of(context).hintColor,	");
buffer.writeln("	              ),	");
buffer.writeln("	            ),	");
buffer.writeln("	          ),	");
buffer.writeln("	        if (widget.errorText != null)	");
buffer.writeln("	          Padding(	");
buffer.writeln("	            padding: const EdgeInsets.only(top: 4, left: 12),	");
buffer.writeln("	            child: Text(	");
buffer.writeln("	              widget.errorText!,	");
buffer.writeln("	              style: Theme.of(context).textTheme.bodySmall?.copyWith(	");
buffer.writeln("	                color: Theme.of(context).colorScheme.error,	");
buffer.writeln("	              ),	");
buffer.writeln("	            ),	");
buffer.writeln("	          ),	");
buffer.writeln("	      ],	");
buffer.writeln("	    );	");
buffer.writeln("	  }	");
buffer.writeln("	}	");
  return buffer.toString().replaceAll('\u00A0', ' ');
}

