String generateradiobuttonClass(
 ) {
   StringBuffer buffer = StringBuffer();
buffer.writeln(r"	import 'package:flutter/material.dart';	");
buffer.writeln(r"		");
buffer.writeln(r"	enum LabelPosition { floating, top, left, inline }	");
buffer.writeln(r"		");
buffer.writeln(r"	class CustomRadioGroup<T> extends FormField<T> {	");
buffer.writeln(r"	  final String? label;	");
buffer.writeln(r"	  final bool isMandatory;	");
buffer.writeln(r"	  final LabelPosition labelPosition;	");
buffer.writeln(r"	  final List<RadioOption<T>> options;	");
buffer.writeln(r"	  final String? helperText;	");
buffer.writeln(r"	  final ValueChanged<T?>? onChanged;	");
buffer.writeln(r"	  final T? selectedValue;	");
buffer.writeln(r"	  final Axis direction;	");
buffer.writeln(r"	  final double spacing;	");
buffer.writeln(r"	  final double runSpacing;	");
buffer.writeln(r"	  final EdgeInsetsGeometry? padding;	");
buffer.writeln(r"	  final TextStyle? labelStyle;	");
buffer.writeln(r"	  final TextStyle? textStyle;	");
buffer.writeln(r"	  final Color? activeColor;	");
buffer.writeln(r"	  final Color? inactiveColor;	");
buffer.writeln(r"	  final bool wrap;	");
buffer.writeln(r"		");
buffer.writeln(r"	  CustomRadioGroup({	");
buffer.writeln(r"	    super.key,	");
buffer.writeln(r"	    this.label,	");
buffer.writeln(r"	    this.isMandatory = false,	");
buffer.writeln(r"	    this.labelPosition = LabelPosition.left,	");
buffer.writeln(r"	    required this.selectedValue,	");
buffer.writeln(r"	    required this.options,	");
buffer.writeln(r"	    this.onChanged,	");
buffer.writeln(r"	    this.helperText,	");
buffer.writeln(r"	    this.direction = Axis.horizontal,	");
buffer.writeln(r"	    this.spacing = 12.0,	");
buffer.writeln(r"	    this.runSpacing = 8.0,	");
buffer.writeln(r"	    this.padding,	");
buffer.writeln(r"	    this.labelStyle,	");
buffer.writeln(r"	    this.textStyle,	");
buffer.writeln(r"	    this.activeColor,	");
buffer.writeln(r"	    this.inactiveColor,	");
buffer.writeln(r"	    this.wrap = false,	");
buffer.writeln(r"	    FormFieldValidator<T>? validator,	");
buffer.writeln(r"	    FormFieldSetter<T>? onSaved,	");
buffer.writeln(r"	  }) : super(	");
buffer.writeln(r"	          initialValue: selectedValue,	");
buffer.writeln(r"	          validator: validator ??	");
buffer.writeln(r"	              (value) {	");
buffer.writeln(r"	                if (isMandatory && value == null) {	");
buffer.writeln(r"	                  return 'Please select ${label ?? 'an option'}';	");
buffer.writeln(r"	                }	");
buffer.writeln(r"	                return null;	");
buffer.writeln(r"	              },	");
buffer.writeln(r"	          onSaved: onSaved,	");
buffer.writeln(r"	          builder: (FormFieldState<T> state) {	");
buffer.writeln(r"	            final theme = Theme.of(state.context);	");
buffer.writeln(r"	            final effectiveActiveColor = activeColor ?? theme.primaryColor;	");
buffer.writeln(r"	            final effectiveInactiveColor = inactiveColor ?? Colors.black54;	");
buffer.writeln(r"	            final effectiveTextStyle = textStyle ??	");
buffer.writeln(r"	                theme.textTheme.bodyMedium?.copyWith(color: Colors.black87);	");
buffer.writeln(r"	            final effectiveLabelStyle = labelStyle ??	");
buffer.writeln('   theme.textTheme.bodyMedium!.copyWith(');
buffer.writeln('      fontWeight: FontWeight.w400,');
buffer.writeln('    );');
buffer.writeln(r"		");
buffer.writeln(r"	            Widget buildRadioOption(RadioOption<T> option) {	");
buffer.writeln(r"	              final bool isSelected = state.value == option.value;	");
buffer.writeln(r"	              return InkWell(	");
buffer.writeln(r"	                onTap: () {	");
buffer.writeln(r"	                  if (state.value != option.value) {	");
buffer.writeln(r"	                    state.didChange(option.value);	");
buffer.writeln(r"	                    onChanged?.call(option.value);	");
buffer.writeln(r"	                  }	");
buffer.writeln(r"	                },	");
buffer.writeln(r"	                borderRadius: BorderRadius.circular(8),	");
buffer.writeln(r"	                child: Padding(	");
buffer.writeln(r"	                  padding: const EdgeInsets.symmetric(vertical: 4),	");
buffer.writeln(r"	                  child: Row(	");
buffer.writeln(r"	                    mainAxisSize: MainAxisSize.min,	");
buffer.writeln(r"	                    children: [	");
buffer.writeln(r"	                      CustomRadioCircle(	");
buffer.writeln(r"	                        isSelected: isSelected,	");
buffer.writeln(r"	                        activeColor: effectiveActiveColor,	");
buffer.writeln(r"	                        inactiveColor: effectiveInactiveColor,	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                      const SizedBox(width: 8),	");
buffer.writeln(r"	                      Text(	");
buffer.writeln(r"	                        option.label,	");
buffer.writeln(r"	                        style: effectiveTextStyle,	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                    ],	");
buffer.writeln(r"	                  ),	");
buffer.writeln(r"	                ),	");
buffer.writeln(r"	              );	");
buffer.writeln(r"	            }	");
buffer.writeln(r"		");
buffer.writeln(r"	            Widget radioGroupContent;	");
buffer.writeln(r"	            if (wrap) {	");
buffer.writeln(r"	              radioGroupContent = Wrap(	");
buffer.writeln(r"	                direction: direction,	");
buffer.writeln(r"	                spacing: spacing,	");
buffer.writeln(r"	                runSpacing: runSpacing,	");
buffer.writeln(r"	                children: options.map(buildRadioOption).toList(),	");
buffer.writeln(r"	              );	");
buffer.writeln(r"	            } else {	");
buffer.writeln(r"	              radioGroupContent = Flex(	");
buffer.writeln(r"	                direction: direction,	");
buffer.writeln(r"	                children: options	");
buffer.writeln(r"	                    .map((option) => Padding(	");
buffer.writeln(r"	                          padding: EdgeInsets.only(	");
buffer.writeln(r"	                            right: direction == Axis.horizontal ? spacing : 0,	");
buffer.writeln(r"	                            bottom: direction == Axis.vertical ? spacing : 0,	");
buffer.writeln(r"	                          ),	");
buffer.writeln(r"	                          child: buildRadioOption(option),	");
buffer.writeln(r"	                        ))	");
buffer.writeln(r"	                    .toList(),	");
buffer.writeln(r"	              );	");
buffer.writeln(r"	            }	");
buffer.writeln(r"		");
buffer.writeln(r"	            Widget labelWidget = label != null	");
buffer.writeln(r"	                ? RichText(	");
buffer.writeln(r"	                    text: TextSpan(	");
buffer.writeln(r"	                      text: label,	");
buffer.writeln(r"	                      style: effectiveLabelStyle,	");
buffer.writeln(r"	                      children: isMandatory	");
buffer.writeln(r"	                          ? [	");
buffer.writeln(r"	                              const TextSpan(	");
buffer.writeln(r"	                                text: ' *',	");
buffer.writeln(r"	                                style: TextStyle(	");
buffer.writeln(r"	                                  color: Colors.red,	");
buffer.writeln(r"	                                  fontWeight: FontWeight.bold,	");
buffer.writeln(r"	                                ),	");
buffer.writeln(r"	                              )	");
buffer.writeln(r"	                            ]	");
buffer.writeln(r"	                          : [],	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                  )	");
buffer.writeln(r"	                : const SizedBox.shrink();	");
buffer.writeln(r"		");
buffer.writeln(r"	            Widget errorWidget = state.hasError	");
buffer.writeln(r"	                ? Padding(	");
buffer.writeln(r"	                    padding: const EdgeInsets.only(top: 4, left: 12),	");
buffer.writeln(r"	                    child: Text(	");
buffer.writeln(r"	                      state.errorText!,	");
buffer.writeln(r"	                      style: theme.textTheme.bodySmall?.copyWith(	");
buffer.writeln(r"	                        color: theme.colorScheme.error,	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                  )	");
buffer.writeln(r"	                : const SizedBox.shrink();	");
buffer.writeln(r"		");
buffer.writeln(r"	            Widget helperWidget = helperText != null	");
buffer.writeln(r"	                ? Padding(	");
buffer.writeln(r"	                    padding: const EdgeInsets.only(top: 4, left: 12),	");
buffer.writeln(r"	                    child: Text(	");
buffer.writeln(r"	                      helperText!,	");
buffer.writeln(r"	                      style: theme.textTheme.bodySmall?.copyWith(	");
buffer.writeln(r"	                        color: theme.hintColor,	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                  )	");
buffer.writeln(r"	                : const SizedBox.shrink();	");
buffer.writeln(r"		");
buffer.writeln(r"	            switch (labelPosition) {	");
buffer.writeln(r"	              case LabelPosition.floating:	");
buffer.writeln(r"	                return Column(	");
buffer.writeln(r"	                  crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln(r"	                  children: [	");
buffer.writeln(r"	                    InputDecorator(	");
buffer.writeln(r"	                      decoration: InputDecoration(	");
buffer.writeln(r"	                        labelText: label,	");
buffer.writeln(r"	                        errorText: state.errorText,	");
buffer.writeln(r"	                        border: const OutlineInputBorder(),	");
buffer.writeln(r"	                        contentPadding: const EdgeInsets.symmetric(	");
buffer.writeln(r"	                          horizontal: 12,	");
buffer.writeln(r"	                          vertical: 16,	");
buffer.writeln(r"	                        ),	");
buffer.writeln(r"	                      ),	");
buffer.writeln(r"	                      child: radioGroupContent,	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                    helperWidget,	");
buffer.writeln(r"	                  ],	");
buffer.writeln(r"	                );	");
buffer.writeln(r"	              case LabelPosition.top:	");
buffer.writeln(r"	                return Column(	");
buffer.writeln(r"	                  crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln(r"	                  children: [	");
buffer.writeln(r"	                    labelWidget,	");
buffer.writeln(r"	                    const SizedBox(height: 8),	");
buffer.writeln(r"	                    radioGroupContent,	");
buffer.writeln(r"	                    errorWidget,	");
buffer.writeln(r"	                    helperWidget,	");
buffer.writeln(r"	                  ],	");
buffer.writeln(r"	                );	");
buffer.writeln(r"	              case LabelPosition.left:	");
buffer.writeln(r"	                return Column(	");
buffer.writeln(r"	                  crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln(r"	                  children: [	");
buffer.writeln(r"	                    Row(	");
buffer.writeln(r"	                      crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln(r"	                      children: [	");
buffer.writeln(r"	                        SizedBox(	");
buffer.writeln(r"	                          width: 120,	");
buffer.writeln(r"	                          child: labelWidget,	");
buffer.writeln(r"	                        ),	");
buffer.writeln(r"	                        const SizedBox(width: 12),	");
buffer.writeln(r"	                        Expanded(child: radioGroupContent),	");
buffer.writeln(r"	                      ],	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                    errorWidget,	");
buffer.writeln(r"	                    helperWidget,	");
buffer.writeln(r"	                  ],	");
buffer.writeln(r"	                );	");
buffer.writeln(r"	              case LabelPosition.inline:	");
buffer.writeln(r"	                return Column(	");
buffer.writeln(r"	                  crossAxisAlignment: CrossAxisAlignment.start,	");
buffer.writeln(r"	                  children: [	");
buffer.writeln(r"	                    Row(	");
buffer.writeln(r"	                      children: [	");
buffer.writeln(r"	                        labelWidget,	");
buffer.writeln(r"	                        const SizedBox(width: 12),	");
buffer.writeln(r"	                        radioGroupContent,	");
buffer.writeln(r"	                      ],	");
buffer.writeln(r"	                    ),	");
buffer.writeln(r"	                    errorWidget,	");
buffer.writeln(r"	                    helperWidget,	");
buffer.writeln(r"	                  ],	");
buffer.writeln(r"	                );	");
buffer.writeln(r"	            }	");
buffer.writeln(r"	          },	");
buffer.writeln(r"	        );	");
buffer.writeln(r"	}	");
buffer.writeln(r"		");
buffer.writeln(r"	class CustomRadioCircle extends StatelessWidget {	");
buffer.writeln(r"	  final bool isSelected;	");
buffer.writeln(r"	  final Color activeColor;	");
buffer.writeln(r"	  final Color inactiveColor;	");
buffer.writeln(r"	  final double size;	");
buffer.writeln(r"		");
buffer.writeln(r"	  const CustomRadioCircle({	");
buffer.writeln(r"	    super.key,	");
buffer.writeln(r"	    required this.isSelected,	");
buffer.writeln(r"	    this.activeColor = Colors.deepPurple,	");
buffer.writeln(r"	    this.inactiveColor = Colors.black54,	");
buffer.writeln(r"	    this.size = 20.0,	");
buffer.writeln(r"	  });	");
buffer.writeln(r"		");
buffer.writeln(r"	  @override	");
buffer.writeln(r"	  Widget build(BuildContext context) {	");
buffer.writeln(r"	    return Container(	");
buffer.writeln(r"	      width: size,	");
buffer.writeln(r"	      height: size,	");
buffer.writeln(r"	      decoration: BoxDecoration(	");
buffer.writeln(r"	        shape: BoxShape.circle,	");
buffer.writeln(r"	        border: Border.all(	");
buffer.writeln(r"	          color: isSelected ? activeColor : inactiveColor,	");
buffer.writeln(r"	          width: 2,	");
buffer.writeln(r"	        ),	");
buffer.writeln(r"	      ),	");
buffer.writeln(r"	      child: isSelected	");
buffer.writeln(r"	          ? Center(	");
buffer.writeln(r"	              child: Container(	");
buffer.writeln(r"	                width: size * 0.5,	");
buffer.writeln(r"	                height: size * 0.5,	");
buffer.writeln(r"	                decoration: BoxDecoration(	");
buffer.writeln(r"	                  color: activeColor,	");
buffer.writeln(r"	                  shape: BoxShape.circle,	");
buffer.writeln(r"	                ),	");
buffer.writeln(r"	              ),	");
buffer.writeln(r"	            )	");
buffer.writeln(r"	          : null,	");
buffer.writeln(r"	    );	");
buffer.writeln(r"	  }	");
buffer.writeln(r"	}	");
buffer.writeln("		");
buffer.writeln("	class RadioOption<T> {	");
buffer.writeln("	  final T value;	");
buffer.writeln("	  final String label;	");
buffer.writeln("	  final Widget? icon;	");
buffer.writeln("		");
buffer.writeln("	  RadioOption({	");
buffer.writeln("	    required this.value,	");
buffer.writeln("	    required this.label,	");
buffer.writeln("	    this.icon,	");
buffer.writeln("	  });	");
buffer.writeln("	}	");

  return buffer.toString().replaceAll('\u00A0', ' ');
}

