String generatedatevalidatorClass(
 ) {
   StringBuffer buffer = StringBuffer();

buffer.writeln(r"	class DateValidators {	");
buffer.writeln(r"	  static String? validateDDMMYYYY(String? value, {String fieldName = 'Date'}) {	");
buffer.writeln(r"	    if (value == null || value.isEmpty) return '$fieldName is required';	");
buffer.writeln(r"	    if (value.length != 10) return '$fieldName must be in dd/MM/yyyy format';	");
buffer.writeln(r"		");
buffer.writeln(r"	    try {	");
buffer.writeln(r"	      final parts = value.split('/');	");
buffer.writeln(r"	      if (parts.length != 3) return '$fieldName format invalid';	");
buffer.writeln(r"		");
buffer.writeln(r"	      final day = int.parse(parts[0]);	");
buffer.writeln(r"	      final month = int.parse(parts[1]);	");
buffer.writeln(r"	      final year = int.parse(parts[2]);	");
buffer.writeln(r"	      final parsed = DateTime(year, month, day);	");
buffer.writeln(r"		");
buffer.writeln(r"	      if (parsed.year != year || parsed.month != month || parsed.day != day) {	");
buffer.writeln(r"	        return 'Invalid $fieldName';	");
buffer.writeln(r"	      }	");
buffer.writeln(r"	    } catch (_) {	");
buffer.writeln(r"	      return 'Invalid $fieldName';	");
buffer.writeln(r"	    }	");
buffer.writeln(r"		");
buffer.writeln(r"	    return null;	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  static String? validateDDMMYYYYHHMM(	");
buffer.writeln(r"	    String? value, {	");
buffer.writeln(r"	    String fieldName = 'DateTime',	");
buffer.writeln(r"	  }) {	");
buffer.writeln(r"	    if (value == null || value.isEmpty) return '$fieldName is required';	");
buffer.writeln(r"	    if (value.length != 16) return '$fieldName must be in dd/MM/yyyy HH:mm format';	");
buffer.writeln(r"		");
buffer.writeln(r"	    try {	");
buffer.writeln(r"	      final parts = value.split(' ');	");
buffer.writeln(r"	      if (parts.length != 2) return '$fieldName format invalid';	");
buffer.writeln(r"	      final datePart = parts[0].split('/');	");
buffer.writeln(r"	      final timePart = parts[1].split(':');	");
buffer.writeln(r"		");
buffer.writeln(r"	      final day = int.parse(datePart[0]);	");
buffer.writeln(r"	      final month = int.parse(datePart[1]);	");
buffer.writeln(r"	      final year = int.parse(datePart[2]);	");
buffer.writeln(r"	      final hour = int.parse(timePart[0]);	");
buffer.writeln(r"	      final minute = int.parse(timePart[1]);	");
buffer.writeln(r"		");
buffer.writeln(r"	      final parsed = DateTime(year, month, day, hour, minute);	");
buffer.writeln(r"	      if (parsed.year != year || 	");
buffer.writeln(r"	          parsed.month != month || 	");
buffer.writeln(r"	          parsed.day != day || 	");
buffer.writeln(r"	          parsed.hour != hour || 	");
buffer.writeln(r"	          parsed.minute != minute) {	");
buffer.writeln(r"	        return 'Invalid $fieldName';	");
buffer.writeln(r"	      }	");
buffer.writeln(r"	      if (hour > 23 || minute > 59) {	");
buffer.writeln(r"	        return 'Invalid time';	");
buffer.writeln(r"	      }	");
buffer.writeln(r"	    } catch (_) {	");
buffer.writeln(r"	      return 'Invalid $fieldName';	");
buffer.writeln(r"	    }	");
buffer.writeln(r"		");
buffer.writeln(r"	    return null;	");
buffer.writeln(r"	  }	");
buffer.writeln(r"		");
buffer.writeln(r"	  static String? validateMMDDYYYY(String? value, {String fieldName = 'Date'}) {	");
buffer.writeln(r"	    if (value == null || value.isEmpty) return '$fieldName is required';	");
buffer.writeln(r"	    if (value.length != 10) return '$fieldName must be in MM/dd/yyyy format';	");
buffer.writeln(r"		");
buffer.writeln(r"	    try {	");
buffer.writeln(r"	      final parts = value.split('/');	");
buffer.writeln(r"	      if (parts.length != 3) return '$fieldName format invalid';	");
buffer.writeln(r"		");
buffer.writeln(r"	      final month = int.parse(parts[0]);	");
buffer.writeln(r"	      final day = int.parse(parts[1]);	");
buffer.writeln(r"	      final year = int.parse(parts[2]);	");
buffer.writeln(r"	      final parsed = DateTime(year, month, day);	");
buffer.writeln(r"		");
buffer.writeln(r"	      if (parsed.year != year || parsed.month != month || parsed.day != day) {	");
buffer.writeln(r"	        return 'Invalid $fieldName';	");
buffer.writeln(r"	      }	");
buffer.writeln(r"	    } catch (_) {	");
buffer.writeln(r"	      return 'Invalid $fieldName';	");
buffer.writeln(r"	    }	");
buffer.writeln(r"		");
buffer.writeln(r"	    return null;	");
buffer.writeln(r"	  }	");
buffer.writeln(r"	}	");
buffer.writeln(r"		");
buffer.writeln(r"		");
buffer.writeln(r"		");
buffer.writeln(r"		");
buffer.writeln(r"		");
buffer.writeln(r"		");
  return buffer.toString().replaceAll('\u00A0', ' ');
}

